#if !defined(AFX__LINE3DH_H__86871A9E_2F3D_4B16_A7D5_4A600E4F7253__INCLUDED_)
#define AFX__LINE3DH_H__86871A9E_2F3D_4B16_A7D5_4A600E4F7253__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// C_Line3DH wrapper class

class C_Line3DH : public CWnd
{
protected:
	DECLARE_DYNCREATE(C_Line3DH)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0xef2b39d6, 0x1f83, 0x4f68, { 0x9a, 0x85, 0x6d, 0x23, 0x78, 0x8c, 0x90, 0x45 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:

// Operations
public:
	void ShowAbout();
	unsigned long GetForeColor();
	long GetLineStyle();
	long GetLinePosition();
	unsigned long GetBackColor();
	void SetForeColor(unsigned long newValue);
	void SetLineStyle(long nNewValue);
	void SetLinePosition(long nNewValue);
	void SetBackColor(unsigned long newValue);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX__LINE3DH_H__86871A9E_2F3D_4B16_A7D5_4A600E4F7253__INCLUDED_)
