// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "crystalreportviewer11.h"

// Dispatch interfaces referenced by this interface
#include "CRVTrackCursorInfo.h"

/////////////////////////////////////////////////////////////////////////////
// CCrystalReportViewer11

IMPLEMENT_DYNCREATE(CCrystalReportViewer11, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CCrystalReportViewer11 properties

/////////////////////////////////////////////////////////////////////////////
// CCrystalReportViewer11 operations

LPUNKNOWN CCrystalReportViewer11::GetReportSource()
{
	LPUNKNOWN result;
	InvokeHelper(0xfa, DISPATCH_PROPERTYGET, VT_UNKNOWN, (void*)&result, NULL);
	return result;
}

void CCrystalReportViewer11::SetReportSource(LPUNKNOWN newValue)
{
	static BYTE parms[] =
		VTS_UNKNOWN;
	InvokeHelper(0xfa, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 newValue);
}

BOOL CCrystalReportViewer11::GetDisplayGroupTree()
{
	BOOL result;
	InvokeHelper(0xfb, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, NULL);
	return result;
}

void CCrystalReportViewer11::SetDisplayGroupTree(BOOL bNewValue)
{
	static BYTE parms[] =
		VTS_BOOL;
	InvokeHelper(0xfb, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 bNewValue);
}

BOOL CCrystalReportViewer11::GetDisplayToolbar()
{
	BOOL result;
	InvokeHelper(0xfc, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, NULL);
	return result;
}

void CCrystalReportViewer11::SetDisplayToolbar(BOOL bNewValue)
{
	static BYTE parms[] =
		VTS_BOOL;
	InvokeHelper(0xfc, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 bNewValue);
}

BOOL CCrystalReportViewer11::GetEnableGroupTree()
{
	BOOL result;
	InvokeHelper(0xfd, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, NULL);
	return result;
}

void CCrystalReportViewer11::SetEnableGroupTree(BOOL bNewValue)
{
	static BYTE parms[] =
		VTS_BOOL;
	InvokeHelper(0xfd, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 bNewValue);
}

BOOL CCrystalReportViewer11::GetEnableNavigationControls()
{
	BOOL result;
	InvokeHelper(0xfe, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, NULL);
	return result;
}

void CCrystalReportViewer11::SetEnableNavigationControls(BOOL bNewValue)
{
	static BYTE parms[] =
		VTS_BOOL;
	InvokeHelper(0xfe, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 bNewValue);
}

BOOL CCrystalReportViewer11::GetEnableStopButton()
{
	BOOL result;
	InvokeHelper(0xff, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, NULL);
	return result;
}

void CCrystalReportViewer11::SetEnableStopButton(BOOL bNewValue)
{
	static BYTE parms[] =
		VTS_BOOL;
	InvokeHelper(0xff, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 bNewValue);
}

BOOL CCrystalReportViewer11::GetEnablePrintButton()
{
	BOOL result;
	InvokeHelper(0x100, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, NULL);
	return result;
}

void CCrystalReportViewer11::SetEnablePrintButton(BOOL bNewValue)
{
	static BYTE parms[] =
		VTS_BOOL;
	InvokeHelper(0x100, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 bNewValue);
}

BOOL CCrystalReportViewer11::GetEnableZoomControl()
{
	BOOL result;
	InvokeHelper(0x101, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, NULL);
	return result;
}

void CCrystalReportViewer11::SetEnableZoomControl(BOOL bNewValue)
{
	static BYTE parms[] =
		VTS_BOOL;
	InvokeHelper(0x101, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 bNewValue);
}

BOOL CCrystalReportViewer11::GetEnableCloseButton()
{
	BOOL result;
	InvokeHelper(0x102, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, NULL);
	return result;
}

void CCrystalReportViewer11::SetEnableCloseButton(BOOL bNewValue)
{
	static BYTE parms[] =
		VTS_BOOL;
	InvokeHelper(0x102, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 bNewValue);
}

BOOL CCrystalReportViewer11::GetEnableProgressControl()
{
	BOOL result;
	InvokeHelper(0x103, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, NULL);
	return result;
}

void CCrystalReportViewer11::SetEnableProgressControl(BOOL bNewValue)
{
	static BYTE parms[] =
		VTS_BOOL;
	InvokeHelper(0x103, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 bNewValue);
}

BOOL CCrystalReportViewer11::GetEnableSearchControl()
{
	BOOL result;
	InvokeHelper(0x104, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, NULL);
	return result;
}

void CCrystalReportViewer11::SetEnableSearchControl(BOOL bNewValue)
{
	static BYTE parms[] =
		VTS_BOOL;
	InvokeHelper(0x104, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 bNewValue);
}

BOOL CCrystalReportViewer11::GetEnableRefreshButton()
{
	BOOL result;
	InvokeHelper(0x105, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, NULL);
	return result;
}

void CCrystalReportViewer11::SetEnableRefreshButton(BOOL bNewValue)
{
	static BYTE parms[] =
		VTS_BOOL;
	InvokeHelper(0x105, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 bNewValue);
}

BOOL CCrystalReportViewer11::GetEnableDrillDown()
{
	BOOL result;
	InvokeHelper(0x106, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, NULL);
	return result;
}

void CCrystalReportViewer11::SetEnableDrillDown(BOOL bNewValue)
{
	static BYTE parms[] =
		VTS_BOOL;
	InvokeHelper(0x106, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 bNewValue);
}

BOOL CCrystalReportViewer11::GetEnableAnimationCtrl()
{
	BOOL result;
	InvokeHelper(0x107, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, NULL);
	return result;
}

void CCrystalReportViewer11::SetEnableAnimationCtrl(BOOL bNewValue)
{
	static BYTE parms[] =
		VTS_BOOL;
	InvokeHelper(0x107, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 bNewValue);
}

BOOL CCrystalReportViewer11::GetEnableSelectExpertButton()
{
	BOOL result;
	InvokeHelper(0x108, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, NULL);
	return result;
}

void CCrystalReportViewer11::SetEnableSelectExpertButton(BOOL bNewValue)
{
	static BYTE parms[] =
		VTS_BOOL;
	InvokeHelper(0x108, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 bNewValue);
}

void CCrystalReportViewer11::ViewReport()
{
	InvokeHelper(0x109, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

BOOL CCrystalReportViewer11::GetEnableToolbar()
{
	BOOL result;
	InvokeHelper(0x154, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, NULL);
	return result;
}

void CCrystalReportViewer11::SetEnableToolbar(BOOL bNewValue)
{
	static BYTE parms[] =
		VTS_BOOL;
	InvokeHelper(0x154, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 bNewValue);
}

BOOL CCrystalReportViewer11::GetDisplayBorder()
{
	BOOL result;
	InvokeHelper(0x155, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, NULL);
	return result;
}

void CCrystalReportViewer11::SetDisplayBorder(BOOL bNewValue)
{
	static BYTE parms[] =
		VTS_BOOL;
	InvokeHelper(0x155, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 bNewValue);
}

BOOL CCrystalReportViewer11::GetDisplayTabs()
{
	BOOL result;
	InvokeHelper(0x156, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, NULL);
	return result;
}

void CCrystalReportViewer11::SetDisplayTabs(BOOL bNewValue)
{
	static BYTE parms[] =
		VTS_BOOL;
	InvokeHelper(0x156, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 bNewValue);
}

BOOL CCrystalReportViewer11::GetDisplayBackgroundEdge()
{
	BOOL result;
	InvokeHelper(0x157, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, NULL);
	return result;
}

void CCrystalReportViewer11::SetDisplayBackgroundEdge(BOOL bNewValue)
{
	static BYTE parms[] =
		VTS_BOOL;
	InvokeHelper(0x157, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 bNewValue);
}

CCRVTrackCursorInfo CCrystalReportViewer11::GetTrackCursorInfo()
{
	LPDISPATCH pDispatch;
	InvokeHelper(0x159, DISPATCH_PROPERTYGET, VT_DISPATCH, (void*)&pDispatch, NULL);
	return CCRVTrackCursorInfo(pDispatch);
}

short CCrystalReportViewer11::GetActiveViewIndex()
{
	short result;
	InvokeHelper(0x15a, DISPATCH_PROPERTYGET, VT_I2, (void*)&result, NULL);
	return result;
}

short CCrystalReportViewer11::GetViewCount()
{
	short result;
	InvokeHelper(0x15b, DISPATCH_PROPERTYGET, VT_I2, (void*)&result, NULL);
	return result;
}

void CCrystalReportViewer11::ActivateView(const VARIANT& Index)
{
	static BYTE parms[] =
		VTS_VARIANT;
	InvokeHelper(0x15c, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 &Index);
}

void CCrystalReportViewer11::AddView(const VARIANT& GroupPath)
{
	static BYTE parms[] =
		VTS_VARIANT;
	InvokeHelper(0x15d, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 &GroupPath);
}

void CCrystalReportViewer11::CloseView(const VARIANT& Index)
{
	static BYTE parms[] =
		VTS_VARIANT;
	InvokeHelper(0x15e, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 &Index);
}

VARIANT CCrystalReportViewer11::GetViewPath(short Index)
{
	VARIANT result;
	static BYTE parms[] =
		VTS_I2;
	InvokeHelper(0x15f, DISPATCH_METHOD, VT_VARIANT, (void*)&result, parms,
		Index);
	return result;
}

void CCrystalReportViewer11::PrintReport()
{
	InvokeHelper(0x160, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CCrystalReportViewer11::Refresh()
{
	InvokeHelper(0x161, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CCrystalReportViewer11::SearchForText(LPCTSTR Text)
{
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x162, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 Text);
}

void CCrystalReportViewer11::ShowFirstPage()
{
	InvokeHelper(0x163, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CCrystalReportViewer11::ShowNextPage()
{
	InvokeHelper(0x164, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CCrystalReportViewer11::ShowPreviousPage()
{
	InvokeHelper(0x165, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CCrystalReportViewer11::ShowLastPage()
{
	InvokeHelper(0x166, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CCrystalReportViewer11::ShowNthPage(short PageNumber)
{
	static BYTE parms[] =
		VTS_I2;
	InvokeHelper(0x167, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 PageNumber);
}

void CCrystalReportViewer11::Zoom(short ZoomLevel)
{
	static BYTE parms[] =
		VTS_I2;
	InvokeHelper(0x168, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 ZoomLevel);
}

long CCrystalReportViewer11::GetCurrentPageNumber()
{
	long result;
	InvokeHelper(0x169, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

void CCrystalReportViewer11::ShowGroup(const VARIANT& GroupPath)
{
	static BYTE parms[] =
		VTS_VARIANT;
	InvokeHelper(0x16a, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 &GroupPath);
}

BOOL CCrystalReportViewer11::GetIsBusy()
{
	BOOL result;
	InvokeHelper(0x16b, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, NULL);
	return result;
}

BOOL CCrystalReportViewer11::GetEnablePopupMenu()
{
	BOOL result;
	InvokeHelper(0x16c, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, NULL);
	return result;
}

void CCrystalReportViewer11::SetEnablePopupMenu(BOOL bNewValue)
{
	static BYTE parms[] =
		VTS_BOOL;
	InvokeHelper(0x16c, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 bNewValue);
}

BOOL CCrystalReportViewer11::GetEnableExportButton()
{
	BOOL result;
	InvokeHelper(0x16d, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, NULL);
	return result;
}

void CCrystalReportViewer11::SetEnableExportButton(BOOL bNewValue)
{
	static BYTE parms[] =
		VTS_BOOL;
	InvokeHelper(0x16d, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 bNewValue);
}

BOOL CCrystalReportViewer11::GetEnableSearchExpertButton()
{
	BOOL result;
	InvokeHelper(0x16f, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, NULL);
	return result;
}

void CCrystalReportViewer11::SetEnableSearchExpertButton(BOOL bNewValue)
{
	static BYTE parms[] =
		VTS_BOOL;
	InvokeHelper(0x16f, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 bNewValue);
}

void CCrystalReportViewer11::SearchByFormula(LPCTSTR formula)
{
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x170, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 formula);
}

CString CCrystalReportViewer11::GetViewName(BSTR* pTabName)
{
	CString result;
	static BYTE parms[] =
		VTS_PBSTR;
	InvokeHelper(0x171, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		pTabName);
	return result;
}

BOOL CCrystalReportViewer11::GetEnableHelpButton()
{
	BOOL result;
	InvokeHelper(0x172, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, NULL);
	return result;
}

void CCrystalReportViewer11::SetEnableHelpButton(BOOL bNewValue)
{
	static BYTE parms[] =
		VTS_BOOL;
	InvokeHelper(0x172, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 bNewValue);
}

VARIANT CCrystalReportViewer11::GetGroup()
{
	VARIANT result;
	InvokeHelper(0x190, DISPATCH_METHOD, VT_VARIANT, (void*)&result, NULL);
	return result;
}

void CCrystalReportViewer11::GetLastPageNumber(long* pageN, BOOL* lastPageKnown)
{
	static BYTE parms[] =
		VTS_PI4 VTS_PBOOL;
	InvokeHelper(0x191, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 pageN, lastPageKnown);
}

void CCrystalReportViewer11::RefreshEx(BOOL refreshServerData)
{
	static BYTE parms[] =
		VTS_BOOL;
	InvokeHelper(0x192, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 refreshServerData);
}

BOOL CCrystalReportViewer11::GetLaunchHTTPHyperlinksInNewBrowser()
{
	BOOL result;
	InvokeHelper(0x1f4, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, NULL);
	return result;
}

void CCrystalReportViewer11::SetLaunchHTTPHyperlinksInNewBrowser(BOOL bNewValue)
{
	static BYTE parms[] =
		VTS_BOOL;
	InvokeHelper(0x1f4, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 bNewValue);
}

unsigned long CCrystalReportViewer11::GetLocaleID()
{
	unsigned long result;
	InvokeHelper(0x259, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

void CCrystalReportViewer11::SetLocaleID(unsigned long newValue)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x259, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 newValue);
}

BOOL CCrystalReportViewer11::GetEnableInteractiveParameterPrompting()
{
	BOOL result;
	InvokeHelper(0x25a, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, NULL);
	return result;
}

void CCrystalReportViewer11::SetEnableInteractiveParameterPrompting(BOOL bNewValue)
{
	static BYTE parms[] =
		VTS_BOOL;
	InvokeHelper(0x25a, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 bNewValue);
}
