//
//  This program code is a part of The Master Scheduler (TMS)
//  and is Copyright (C) 1991-2004 Schedule Masters, Inc.
//  All rights reserved.
//
#define EXCEL_DIMENSIONS                 0x00
#define EXCEL_BLANK                      0x01
#define EXCEL_INTEGER                    0x02
#define EXCEL_NUMBER                     0x03
#define EXCEL_LABEL                      0x04
#define EXCEL_BOOLERR                    0x05
#define EXCEL_FORMULA                    0x06
#define EXCEL_STRING                     0x07
#define EXCEL_ROW                        0x08
#define EXCEL_BOF                        0x09
#define EXCEL_EOF                        0x0A
#define EXCEL_INDEX                      0x0B
#define EXCEL_CALCCOUNT                  0x0C
#define EXCEL_CALCMODE                   0x0D
#define EXCEL_PRECISION                  0x0E
#define EXCEL_REFMODE                    0x0F
#define EXCEL_DELTA                      0x10
#define EXCEL_ITERATION                  0x11
#define EXCEL_PROTECT                    0x12
#define EXCEL_PASSWORD                   0x13
#define EXCEL_HEADER                     0x14
#define EXCEL_FOOTER                     0x15
#define EXCEL_EXTERNCOUNT                0x16
#define EXCEL_EXTERNSHEET                0x17
#define EXCEL_NAME                       0x18
#define EXCEL_WINDOW_PROTECT             0x19
#define EXCEL_VERTICAL_PAGE_BREAKS       0x1A
#define EXCEL_HORIZONTAL_PAGE_BREAKS     0x1B
#define EXCEL_NOTE                       0x1C
#define EXCEL_SELECTION                  0x1D
#define EXCEL_FORMAT                     0x1E
#define EXCEL_FORMATCOUNT                0x1F
#define EXCEL_COLUMN_DEFAULT             0x20
#define EXCEL_ARRAY                      0x21
#define EXCEL_1904                       0x22
#define EXCEL_EXTERNNAME                 0x23
#define EXCEL_COLWIDTH                   0x24
#define EXCEL_DEFAULT_ROW_HEIGHT         0x25
#define EXCEL_LEFT_MARGIN                0x26
#define EXCEL_RIGHT_MARGIN               0x27
#define EXCEL_TOP_MARGIN                 0x28
#define EXCEL_BOTTOM_MARGIN              0x29
#define EXCEL_PRINT_ROW_HEADERS          0x2A
#define EXCEL_PRINT_GRIDLINES            0x2B
#define EXCEL_FILEPASS                   0x2F
#define EXCEL_FONT                       0x31
#define EXCEL_FONT2                      0x32
#define EXCEL_TABLE                      0x36
#define EXCEL_TABLE2                     0x37
#define EXCEL_CONTINUE                   0x3C
#define EXCEL_WINDOW1                    0x3D
#define EXCEL_WINDOW2                    0x3E
#define EXCEL_BACKUP                     0x40
#define EXCEL_PANE                       0x41
