// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "f1bookview.h"

// Dispatch interfaces referenced by this interface
#include "f1rangeref.h"
#include "f1objpos.h"
#include "f1rect.h"
#include "f1numberformat.h"
#include "f1cellformat.h"


/////////////////////////////////////////////////////////////////////////////
// CF1BookView properties

unsigned long CF1BookView::GetBackColor()
{
	unsigned long result;
	GetProperty(0x3, VT_I4, (void*)&result);
	return result;
}

void CF1BookView::SetBackColor(unsigned long propVal)
{
	SetProperty(0x3, VT_I4, propVal);
}

long CF1BookView::GetCol()
{
	long result;
	GetProperty(0x4, VT_I4, (void*)&result);
	return result;
}

void CF1BookView::SetCol(long propVal)
{
	SetProperty(0x4, VT_I4, propVal);
}

long CF1BookView::GetRow()
{
	long result;
	GetProperty(0x5, VT_I4, (void*)&result);
	return result;
}

void CF1BookView::SetRow(long propVal)
{
	SetProperty(0x5, VT_I4, propVal);
}

long CF1BookView::GetShowHScrollBar()
{
	long result;
	GetProperty(0x6, VT_I4, (void*)&result);
	return result;
}

void CF1BookView::SetShowHScrollBar(long propVal)
{
	SetProperty(0x6, VT_I4, propVal);
}

CString CF1BookView::GetText()
{
	CString result;
	GetProperty(0x7, VT_BSTR, (void*)&result);
	return result;
}

void CF1BookView::SetText(LPCTSTR propVal)
{
	SetProperty(0x7, VT_BSTR, propVal);
}

double CF1BookView::GetNumber()
{
	double result;
	GetProperty(0x8, VT_R8, (void*)&result);
	return result;
}

void CF1BookView::SetNumber(double propVal)
{
	SetProperty(0x8, VT_R8, propVal);
}

CString CF1BookView::GetFormula()
{
	CString result;
	GetProperty(0x9, VT_BSTR, (void*)&result);
	return result;
}

void CF1BookView::SetFormula(LPCTSTR propVal)
{
	SetProperty(0x9, VT_BSTR, propVal);
}

long CF1BookView::GetFixedCol()
{
	long result;
	GetProperty(0xa, VT_I4, (void*)&result);
	return result;
}

void CF1BookView::SetFixedCol(long propVal)
{
	SetProperty(0xa, VT_I4, propVal);
}

long CF1BookView::GetFixedCols()
{
	long result;
	GetProperty(0xb, VT_I4, (void*)&result);
	return result;
}

void CF1BookView::SetFixedCols(long propVal)
{
	SetProperty(0xb, VT_I4, propVal);
}

long CF1BookView::GetFixedRow()
{
	long result;
	GetProperty(0xc, VT_I4, (void*)&result);
	return result;
}

void CF1BookView::SetFixedRow(long propVal)
{
	SetProperty(0xc, VT_I4, propVal);
}

long CF1BookView::GetFixedRows()
{
	long result;
	GetProperty(0xd, VT_I4, (void*)&result);
	return result;
}

void CF1BookView::SetFixedRows(long propVal)
{
	SetProperty(0xd, VT_I4, propVal);
}

BOOL CF1BookView::GetShowGridLines()
{
	BOOL result;
	GetProperty(0xe, VT_BOOL, (void*)&result);
	return result;
}

void CF1BookView::SetShowGridLines(BOOL propVal)
{
	SetProperty(0xe, VT_BOOL, propVal);
}

BOOL CF1BookView::GetShowRowHeading()
{
	BOOL result;
	GetProperty(0xf, VT_BOOL, (void*)&result);
	return result;
}

void CF1BookView::SetShowRowHeading(BOOL propVal)
{
	SetProperty(0xf, VT_BOOL, propVal);
}

long CF1BookView::GetShowSelections()
{
	long result;
	GetProperty(0x10, VT_I4, (void*)&result);
	return result;
}

void CF1BookView::SetShowSelections(long propVal)
{
	SetProperty(0x10, VT_I4, propVal);
}

long CF1BookView::GetLeftCol()
{
	long result;
	GetProperty(0x11, VT_I4, (void*)&result);
	return result;
}

void CF1BookView::SetLeftCol(long propVal)
{
	SetProperty(0x11, VT_I4, propVal);
}

long CF1BookView::GetMaxCol()
{
	long result;
	GetProperty(0x12, VT_I4, (void*)&result);
	return result;
}

void CF1BookView::SetMaxCol(long propVal)
{
	SetProperty(0x12, VT_I4, propVal);
}

long CF1BookView::GetMaxRow()
{
	long result;
	GetProperty(0x13, VT_I4, (void*)&result);
	return result;
}

void CF1BookView::SetMaxRow(long propVal)
{
	SetProperty(0x13, VT_I4, propVal);
}

long CF1BookView::GetTopRow()
{
	long result;
	GetProperty(0x14, VT_I4, (void*)&result);
	return result;
}

void CF1BookView::SetTopRow(long propVal)
{
	SetProperty(0x14, VT_I4, propVal);
}

BOOL CF1BookView::GetAllowResize()
{
	BOOL result;
	GetProperty(0x15, VT_BOOL, (void*)&result);
	return result;
}

void CF1BookView::SetAllowResize(BOOL propVal)
{
	SetProperty(0x15, VT_BOOL, propVal);
}

BOOL CF1BookView::GetAllowSelections()
{
	BOOL result;
	GetProperty(0x16, VT_BOOL, (void*)&result);
	return result;
}

void CF1BookView::SetAllowSelections(BOOL propVal)
{
	SetProperty(0x16, VT_BOOL, propVal);
}

BOOL CF1BookView::GetAllowFormulas()
{
	BOOL result;
	GetProperty(0x17, VT_BOOL, (void*)&result);
	return result;
}

void CF1BookView::SetAllowFormulas(BOOL propVal)
{
	SetProperty(0x17, VT_BOOL, propVal);
}

BOOL CF1BookView::GetAllowInCellEditing()
{
	BOOL result;
	GetProperty(0x18, VT_BOOL, (void*)&result);
	return result;
}

void CF1BookView::SetAllowInCellEditing(BOOL propVal)
{
	SetProperty(0x18, VT_BOOL, propVal);
}

long CF1BookView::GetShowVScrollBar()
{
	long result;
	GetProperty(0x19, VT_I4, (void*)&result);
	return result;
}

void CF1BookView::SetShowVScrollBar(long propVal)
{
	SetProperty(0x19, VT_I4, propVal);
}

BOOL CF1BookView::GetAllowFillRange()
{
	BOOL result;
	GetProperty(0x1a, VT_BOOL, (void*)&result);
	return result;
}

void CF1BookView::SetAllowFillRange(BOOL propVal)
{
	SetProperty(0x1a, VT_BOOL, propVal);
}

BOOL CF1BookView::GetAllowMoveRange()
{
	BOOL result;
	GetProperty(0x1b, VT_BOOL, (void*)&result);
	return result;
}

void CF1BookView::SetAllowMoveRange(BOOL propVal)
{
	SetProperty(0x1b, VT_BOOL, propVal);
}

long CF1BookView::GetSelStartCol()
{
	long result;
	GetProperty(0x1c, VT_I4, (void*)&result);
	return result;
}

void CF1BookView::SetSelStartCol(long propVal)
{
	SetProperty(0x1c, VT_I4, propVal);
}

long CF1BookView::GetSelStartRow()
{
	long result;
	GetProperty(0x1d, VT_I4, (void*)&result);
	return result;
}

void CF1BookView::SetSelStartRow(long propVal)
{
	SetProperty(0x1d, VT_I4, propVal);
}

long CF1BookView::GetSelEndCol()
{
	long result;
	GetProperty(0x1e, VT_I4, (void*)&result);
	return result;
}

void CF1BookView::SetSelEndCol(long propVal)
{
	SetProperty(0x1e, VT_I4, propVal);
}

long CF1BookView::GetSelEndRow()
{
	long result;
	GetProperty(0x1f, VT_I4, (void*)&result);
	return result;
}

void CF1BookView::SetSelEndRow(long propVal)
{
	SetProperty(0x1f, VT_I4, propVal);
}

unsigned long CF1BookView::GetExtraColor()
{
	unsigned long result;
	GetProperty(0x20, VT_I4, (void*)&result);
	return result;
}

void CF1BookView::SetExtraColor(unsigned long propVal)
{
	SetProperty(0x20, VT_I4, propVal);
}

CString CF1BookView::GetFileName()
{
	CString result;
	GetProperty(0x21, VT_BSTR, (void*)&result);
	return result;
}

void CF1BookView::SetFileName(LPCTSTR propVal)
{
	SetProperty(0x21, VT_BSTR, propVal);
}

BOOL CF1BookView::GetAutoRecalc()
{
	BOOL result;
	GetProperty(0x22, VT_BOOL, (void*)&result);
	return result;
}

void CF1BookView::SetAutoRecalc(BOOL propVal)
{
	SetProperty(0x22, VT_BOOL, propVal);
}

BOOL CF1BookView::GetPrintGridLines()
{
	BOOL result;
	GetProperty(0x23, VT_BOOL, (void*)&result);
	return result;
}

void CF1BookView::SetPrintGridLines(BOOL propVal)
{
	SetProperty(0x23, VT_BOOL, propVal);
}

BOOL CF1BookView::GetPrintRowHeading()
{
	BOOL result;
	GetProperty(0x24, VT_BOOL, (void*)&result);
	return result;
}

void CF1BookView::SetPrintRowHeading(BOOL propVal)
{
	SetProperty(0x24, VT_BOOL, propVal);
}

BOOL CF1BookView::GetPrintHCenter()
{
	BOOL result;
	GetProperty(0x25, VT_BOOL, (void*)&result);
	return result;
}

void CF1BookView::SetPrintHCenter(BOOL propVal)
{
	SetProperty(0x25, VT_BOOL, propVal);
}

BOOL CF1BookView::GetPrintVCenter()
{
	BOOL result;
	GetProperty(0x26, VT_BOOL, (void*)&result);
	return result;
}

void CF1BookView::SetPrintVCenter(BOOL propVal)
{
	SetProperty(0x26, VT_BOOL, propVal);
}

BOOL CF1BookView::GetPrintLeftToRight()
{
	BOOL result;
	GetProperty(0x27, VT_BOOL, (void*)&result);
	return result;
}

void CF1BookView::SetPrintLeftToRight(BOOL propVal)
{
	SetProperty(0x27, VT_BOOL, propVal);
}

CString CF1BookView::GetPrintHeader()
{
	CString result;
	GetProperty(0x28, VT_BSTR, (void*)&result);
	return result;
}

void CF1BookView::SetPrintHeader(LPCTSTR propVal)
{
	SetProperty(0x28, VT_BSTR, propVal);
}

CString CF1BookView::GetPrintFooter()
{
	CString result;
	GetProperty(0x29, VT_BSTR, (void*)&result);
	return result;
}

void CF1BookView::SetPrintFooter(LPCTSTR propVal)
{
	SetProperty(0x29, VT_BSTR, propVal);
}

double CF1BookView::GetPrintLeftMargin()
{
	double result;
	GetProperty(0x2a, VT_R8, (void*)&result);
	return result;
}

void CF1BookView::SetPrintLeftMargin(double propVal)
{
	SetProperty(0x2a, VT_R8, propVal);
}

double CF1BookView::GetPrintTopMargin()
{
	double result;
	GetProperty(0x2b, VT_R8, (void*)&result);
	return result;
}

void CF1BookView::SetPrintTopMargin(double propVal)
{
	SetProperty(0x2b, VT_R8, propVal);
}

double CF1BookView::GetPrintRightMargin()
{
	double result;
	GetProperty(0x2c, VT_R8, (void*)&result);
	return result;
}

void CF1BookView::SetPrintRightMargin(double propVal)
{
	SetProperty(0x2c, VT_R8, propVal);
}

double CF1BookView::GetPrintBottomMargin()
{
	double result;
	GetProperty(0x2d, VT_R8, (void*)&result);
	return result;
}

void CF1BookView::SetPrintBottomMargin(double propVal)
{
	SetProperty(0x2d, VT_R8, propVal);
}

CString CF1BookView::GetPrintArea()
{
	CString result;
	GetProperty(0x2e, VT_BSTR, (void*)&result);
	return result;
}

void CF1BookView::SetPrintArea(LPCTSTR propVal)
{
	SetProperty(0x2e, VT_BSTR, propVal);
}

CString CF1BookView::GetPrintTitles()
{
	CString result;
	GetProperty(0x2f, VT_BSTR, (void*)&result);
	return result;
}

void CF1BookView::SetPrintTitles(LPCTSTR propVal)
{
	SetProperty(0x2f, VT_BSTR, propVal);
}

BOOL CF1BookView::GetPrintNoColor()
{
	BOOL result;
	GetProperty(0x30, VT_BOOL, (void*)&result);
	return result;
}

void CF1BookView::SetPrintNoColor(BOOL propVal)
{
	SetProperty(0x30, VT_BOOL, propVal);
}

CString CF1BookView::GetSelection()
{
	CString result;
	GetProperty(0x31, VT_BSTR, (void*)&result);
	return result;
}

void CF1BookView::SetSelection(LPCTSTR propVal)
{
	SetProperty(0x31, VT_BSTR, propVal);
}

CString CF1BookView::GetTableName()
{
	CString result;
	GetProperty(0x32, VT_BSTR, (void*)&result);
	return result;
}

void CF1BookView::SetTableName(LPCTSTR propVal)
{
	SetProperty(0x32, VT_BSTR, propVal);
}

BOOL CF1BookView::GetShowColHeading()
{
	BOOL result;
	GetProperty(0x3b, VT_BOOL, (void*)&result);
	return result;
}

void CF1BookView::SetShowColHeading(BOOL propVal)
{
	SetProperty(0x3b, VT_BOOL, propVal);
}

BOOL CF1BookView::GetPrintColHeading()
{
	BOOL result;
	GetProperty(0x3c, VT_BOOL, (void*)&result);
	return result;
}

void CF1BookView::SetPrintColHeading(BOOL propVal)
{
	SetProperty(0x3c, VT_BOOL, propVal);
}

CString CF1BookView::GetEntry()
{
	CString result;
	GetProperty(0x3d, VT_BSTR, (void*)&result);
	return result;
}

void CF1BookView::SetEntry(LPCTSTR propVal)
{
	SetProperty(0x3d, VT_BSTR, propVal);
}

BOOL CF1BookView::GetRepaint()
{
	BOOL result;
	GetProperty(0x3e, VT_BOOL, (void*)&result);
	return result;
}

void CF1BookView::SetRepaint(BOOL propVal)
{
	SetProperty(0x3e, VT_BOOL, propVal);
}

BOOL CF1BookView::GetAllowArrows()
{
	BOOL result;
	GetProperty(0x3f, VT_BOOL, (void*)&result);
	return result;
}

void CF1BookView::SetAllowArrows(BOOL propVal)
{
	SetProperty(0x3f, VT_BOOL, propVal);
}

BOOL CF1BookView::GetAllowTabs()
{
	BOOL result;
	GetProperty(0x40, VT_BOOL, (void*)&result);
	return result;
}

void CF1BookView::SetAllowTabs(BOOL propVal)
{
	SetProperty(0x40, VT_BOOL, propVal);
}

CString CF1BookView::GetFormattedText()
{
	CString result;
	GetProperty(0x41, VT_BSTR, (void*)&result);
	return result;
}

void CF1BookView::SetFormattedText(LPCTSTR propVal)
{
	SetProperty(0x41, VT_BSTR, propVal);
}

BOOL CF1BookView::GetRowMode()
{
	BOOL result;
	GetProperty(0x42, VT_BOOL, (void*)&result);
	return result;
}

void CF1BookView::SetRowMode(BOOL propVal)
{
	SetProperty(0x42, VT_BOOL, propVal);
}

BOOL CF1BookView::GetAllowDelete()
{
	BOOL result;
	GetProperty(0x43, VT_BOOL, (void*)&result);
	return result;
}

void CF1BookView::SetAllowDelete(BOOL propVal)
{
	SetProperty(0x43, VT_BOOL, propVal);
}

BOOL CF1BookView::GetEnableProtection()
{
	BOOL result;
	GetProperty(0x44, VT_BOOL, (void*)&result);
	return result;
}

void CF1BookView::SetEnableProtection(BOOL propVal)
{
	SetProperty(0x44, VT_BOOL, propVal);
}

long CF1BookView::GetMinCol()
{
	long result;
	GetProperty(0x45, VT_I4, (void*)&result);
	return result;
}

void CF1BookView::SetMinCol(long propVal)
{
	SetProperty(0x45, VT_I4, propVal);
}

long CF1BookView::GetMinRow()
{
	long result;
	GetProperty(0x46, VT_I4, (void*)&result);
	return result;
}

void CF1BookView::SetMinRow(long propVal)
{
	SetProperty(0x46, VT_I4, propVal);
}

BOOL CF1BookView::GetAllowEditHeaders()
{
	BOOL result;
	GetProperty(0x48, VT_BOOL, (void*)&result);
	return result;
}

void CF1BookView::SetAllowEditHeaders(BOOL propVal)
{
	SetProperty(0x48, VT_BOOL, propVal);
}

BOOL CF1BookView::GetAllowObjSelections()
{
	BOOL result;
	GetProperty(0x4b, VT_BOOL, (void*)&result);
	return result;
}

void CF1BookView::SetAllowObjSelections(BOOL propVal)
{
	SetProperty(0x4b, VT_BOOL, propVal);
}

CString CF1BookView::GetClip()
{
	CString result;
	GetProperty(0x4e, VT_BSTR, (void*)&result);
	return result;
}

void CF1BookView::SetClip(LPCTSTR propVal)
{
	SetProperty(0x4e, VT_BSTR, propVal);
}

CString CF1BookView::GetClipValues()
{
	CString result;
	GetProperty(0x4f, VT_BSTR, (void*)&result);
	return result;
}

void CF1BookView::SetClipValues(LPCTSTR propVal)
{
	SetProperty(0x4f, VT_BSTR, propVal);
}

BOOL CF1BookView::GetPrintLandscape()
{
	BOOL result;
	GetProperty(0x50, VT_BOOL, (void*)&result);
	return result;
}

void CF1BookView::SetPrintLandscape(BOOL propVal)
{
	SetProperty(0x50, VT_BOOL, propVal);
}

CString CF1BookView::GetAppName()
{
	CString result;
	GetProperty(0x51, VT_BSTR, (void*)&result);
	return result;
}

void CF1BookView::SetAppName(LPCTSTR propVal)
{
	SetProperty(0x51, VT_BSTR, propVal);
}

short CF1BookView::GetHdrHeight()
{
	short result;
	GetProperty(0x52, VT_I2, (void*)&result);
	return result;
}

void CF1BookView::SetHdrHeight(short propVal)
{
	SetProperty(0x52, VT_I2, propVal);
}

short CF1BookView::GetHdrWidth()
{
	short result;
	GetProperty(0x53, VT_I2, (void*)&result);
	return result;
}

void CF1BookView::SetHdrWidth(short propVal)
{
	SetProperty(0x53, VT_I2, propVal);
}

CString CF1BookView::GetNumberFormat()
{
	CString result;
	GetProperty(0x54, VT_BSTR, (void*)&result);
	return result;
}

void CF1BookView::SetNumberFormat(LPCTSTR propVal)
{
	SetProperty(0x54, VT_BSTR, propVal);
}

CString CF1BookView::GetTopLeftText()
{
	CString result;
	GetProperty(0x55, VT_BSTR, (void*)&result);
	return result;
}

void CF1BookView::SetTopLeftText(LPCTSTR propVal)
{
	SetProperty(0x55, VT_BSTR, propVal);
}

BOOL CF1BookView::GetEnterMovesDown()
{
	BOOL result;
	GetProperty(0x56, VT_BOOL, (void*)&result);
	return result;
}

void CF1BookView::SetEnterMovesDown(BOOL propVal)
{
	SetProperty(0x56, VT_BOOL, propVal);
}

long CF1BookView::GetLastCol()
{
	long result;
	GetProperty(0x57, VT_I4, (void*)&result);
	return result;
}

void CF1BookView::SetLastCol(long propVal)
{
	SetProperty(0x57, VT_I4, propVal);
}

long CF1BookView::GetLastRow()
{
	long result;
	GetProperty(0x58, VT_I4, (void*)&result);
	return result;
}

void CF1BookView::SetLastRow(long propVal)
{
	SetProperty(0x58, VT_I4, propVal);
}

BOOL CF1BookView::GetLogical()
{
	BOOL result;
	GetProperty(0x59, VT_BOOL, (void*)&result);
	return result;
}

void CF1BookView::SetLogical(BOOL propVal)
{
	SetProperty(0x59, VT_BOOL, propVal);
}

short CF1BookView::GetViewScale()
{
	short result;
	GetProperty(0x5c, VT_I2, (void*)&result);
	return result;
}

void CF1BookView::SetViewScale(short propVal)
{
	SetProperty(0x5c, VT_I2, propVal);
}

short CF1BookView::GetSelectionCount()
{
	short result;
	GetProperty(0x5d, VT_I2, (void*)&result);
	return result;
}

void CF1BookView::SetSelectionCount(short propVal)
{
	SetProperty(0x5d, VT_I2, propVal);
}

CString CF1BookView::GetTitle()
{
	CString result;
	GetProperty(0x5e, VT_BSTR, (void*)&result);
	return result;
}

void CF1BookView::SetTitle(LPCTSTR propVal)
{
	SetProperty(0x5e, VT_BSTR, propVal);
}

short CF1BookView::GetType()
{
	short result;
	GetProperty(0x5f, VT_I2, (void*)&result);
	return result;
}

void CF1BookView::SetType(short propVal)
{
	SetProperty(0x5f, VT_I2, propVal);
}

BOOL CF1BookView::GetShowFormulas()
{
	BOOL result;
	GetProperty(0x60, VT_BOOL, (void*)&result);
	return result;
}

void CF1BookView::SetShowFormulas(BOOL propVal)
{
	SetProperty(0x60, VT_BOOL, propVal);
}

BOOL CF1BookView::GetShowZeroValues()
{
	BOOL result;
	GetProperty(0x61, VT_BOOL, (void*)&result);
	return result;
}

void CF1BookView::SetShowZeroValues(BOOL propVal)
{
	SetProperty(0x61, VT_BOOL, propVal);
}

BOOL CF1BookView::GetScrollToLastRC()
{
	BOOL result;
	GetProperty(0x64, VT_BOOL, (void*)&result);
	return result;
}

void CF1BookView::SetScrollToLastRC(BOOL propVal)
{
	SetProperty(0x64, VT_BOOL, propVal);
}

BOOL CF1BookView::GetModified()
{
	BOOL result;
	GetProperty(0x65, VT_BOOL, (void*)&result);
	return result;
}

void CF1BookView::SetModified(BOOL propVal)
{
	SetProperty(0x65, VT_BOOL, propVal);
}

long CF1BookView::GetPrintDevMode()
{
	long result;
	GetProperty(0x68, VT_I4, (void*)&result);
	return result;
}

void CF1BookView::SetPrintDevMode(long propVal)
{
	SetProperty(0x68, VT_I4, propVal);
}

long CF1BookView::GetNumSheets()
{
	long result;
	GetProperty(0x69, VT_I4, (void*)&result);
	return result;
}

void CF1BookView::SetNumSheets(long propVal)
{
	SetProperty(0x69, VT_I4, propVal);
}

long CF1BookView::GetSheet()
{
	long result;
	GetProperty(0x6a, VT_I4, (void*)&result);
	return result;
}

void CF1BookView::SetSheet(long propVal)
{
	SetProperty(0x6a, VT_I4, propVal);
}

long CF1BookView::GetColWidthUnits()
{
	long result;
	GetProperty(0x6b, VT_I4, (void*)&result);
	return result;
}

void CF1BookView::SetColWidthUnits(long propVal)
{
	SetProperty(0x6b, VT_I4, propVal);
}

BOOL CF1BookView::GetShowTypeMarkers()
{
	BOOL result;
	GetProperty(0x6c, VT_BOOL, (void*)&result);
	return result;
}

void CF1BookView::SetShowTypeMarkers(BOOL propVal)
{
	SetProperty(0x6c, VT_BOOL, propVal);
}

long CF1BookView::GetShowTabs()
{
	long result;
	GetProperty(0x6d, VT_I4, (void*)&result);
	return result;
}

void CF1BookView::SetShowTabs(long propVal)
{
	SetProperty(0x6d, VT_I4, propVal);
}

BOOL CF1BookView::GetShowEditBar()
{
	BOOL result;
	GetProperty(0x6e, VT_BOOL, (void*)&result);
	return result;
}

void CF1BookView::SetShowEditBar(BOOL propVal)
{
	SetProperty(0x6e, VT_BOOL, propVal);
}

BOOL CF1BookView::GetShowEditBarCellRef()
{
	BOOL result;
	GetProperty(0x6f, VT_BOOL, (void*)&result);
	return result;
}

void CF1BookView::SetShowEditBarCellRef(BOOL propVal)
{
	SetProperty(0x6f, VT_BOOL, propVal);
}

BOOL CF1BookView::GetAllowAutoFill()
{
	BOOL result;
	GetProperty(0x70, VT_BOOL, (void*)&result);
	return result;
}

void CF1BookView::SetAllowAutoFill(BOOL propVal)
{
	SetProperty(0x70, VT_BOOL, propVal);
}

BOOL CF1BookView::GetCompressed()
{
	BOOL result;
	GetProperty(0x12b, VT_BOOL, (void*)&result);
	return result;
}

void CF1BookView::SetCompressed(BOOL propVal)
{
	SetProperty(0x12b, VT_BOOL, propVal);
}

CString CF1BookView::GetFontName()
{
	CString result;
	GetProperty(0x514, VT_BSTR, (void*)&result);
	return result;
}

void CF1BookView::SetFontName(LPCTSTR propVal)
{
	SetProperty(0x514, VT_BSTR, propVal);
}

short CF1BookView::GetFontSize()
{
	short result;
	GetProperty(0x515, VT_I2, (void*)&result);
	return result;
}

void CF1BookView::SetFontSize(short propVal)
{
	SetProperty(0x515, VT_I2, propVal);
}

BOOL CF1BookView::GetFontBold()
{
	BOOL result;
	GetProperty(0x516, VT_BOOL, (void*)&result);
	return result;
}

void CF1BookView::SetFontBold(BOOL propVal)
{
	SetProperty(0x516, VT_BOOL, propVal);
}

BOOL CF1BookView::GetFontItalic()
{
	BOOL result;
	GetProperty(0x517, VT_BOOL, (void*)&result);
	return result;
}

void CF1BookView::SetFontItalic(BOOL propVal)
{
	SetProperty(0x517, VT_BOOL, propVal);
}

BOOL CF1BookView::GetFontUnderline()
{
	BOOL result;
	GetProperty(0x518, VT_BOOL, (void*)&result);
	return result;
}

void CF1BookView::SetFontUnderline(BOOL propVal)
{
	SetProperty(0x518, VT_BOOL, propVal);
}

BOOL CF1BookView::GetFontStrikeout()
{
	BOOL result;
	GetProperty(0x519, VT_BOOL, (void*)&result);
	return result;
}

void CF1BookView::SetFontStrikeout(BOOL propVal)
{
	SetProperty(0x519, VT_BOOL, propVal);
}

unsigned long CF1BookView::GetFontColor()
{
	unsigned long result;
	GetProperty(0x51a, VT_I4, (void*)&result);
	return result;
}

void CF1BookView::SetFontColor(unsigned long propVal)
{
	SetProperty(0x51a, VT_I4, propVal);
}

long CF1BookView::GetFontCharSet()
{
	long result;
	GetProperty(0x599, VT_I4, (void*)&result);
	return result;
}

void CF1BookView::SetFontCharSet(long propVal)
{
	SetProperty(0x599, VT_I4, propVal);
}

long CF1BookView::GetHAlign()
{
	long result;
	GetProperty(0x51b, VT_I4, (void*)&result);
	return result;
}

void CF1BookView::SetHAlign(long propVal)
{
	SetProperty(0x51b, VT_I4, propVal);
}

BOOL CF1BookView::GetWordWrap()
{
	BOOL result;
	GetProperty(0x51c, VT_BOOL, (void*)&result);
	return result;
}

void CF1BookView::SetWordWrap(BOOL propVal)
{
	SetProperty(0x51c, VT_BOOL, propVal);
}

long CF1BookView::GetVAlign()
{
	long result;
	GetProperty(0x51d, VT_I4, (void*)&result);
	return result;
}

void CF1BookView::SetVAlign(long propVal)
{
	SetProperty(0x51d, VT_I4, propVal);
}

double CF1BookView::GetPrintHeaderMargin()
{
	double result;
	GetProperty(0x51f, VT_R8, (void*)&result);
	return result;
}

void CF1BookView::SetPrintHeaderMargin(double propVal)
{
	SetProperty(0x51f, VT_R8, propVal);
}

double CF1BookView::GetPrintFooterMargin()
{
	double result;
	GetProperty(0x520, VT_R8, (void*)&result);
	return result;
}

void CF1BookView::SetPrintFooterMargin(double propVal)
{
	SetProperty(0x520, VT_R8, propVal);
}

CString CF1BookView::GetFormulaLocal()
{
	CString result;
	GetProperty(0x52e, VT_BSTR, (void*)&result);
	return result;
}

void CF1BookView::SetFormulaLocal(LPCTSTR propVal)
{
	SetProperty(0x52e, VT_BSTR, propVal);
}

CString CF1BookView::GetNumberFormatLocal()
{
	CString result;
	GetProperty(0x532, VT_BSTR, (void*)&result);
	return result;
}

void CF1BookView::SetNumberFormatLocal(LPCTSTR propVal)
{
	SetProperty(0x532, VT_BSTR, propVal);
}

CString CF1BookView::GetSelectionLocal()
{
	CString result;
	GetProperty(0x533, VT_BSTR, (void*)&result);
	return result;
}

void CF1BookView::SetSelectionLocal(LPCTSTR propVal)
{
	SetProperty(0x533, VT_BSTR, propVal);
}

CString CF1BookView::GetDataTransferRange()
{
	CString result;
	GetProperty(0x536, VT_BSTR, (void*)&result);
	return result;
}

void CF1BookView::SetDataTransferRange(LPCTSTR propVal)
{
	SetProperty(0x536, VT_BSTR, propVal);
}

BOOL CF1BookView::GetCanEditPaste()
{
	BOOL result;
	GetProperty(0x540, VT_BOOL, (void*)&result);
	return result;
}

void CF1BookView::SetCanEditPaste(BOOL propVal)
{
	SetProperty(0x540, VT_BOOL, propVal);
}

short CF1BookView::GetObjPatternStyle()
{
	short result;
	GetProperty(0x54a, VT_I2, (void*)&result);
	return result;
}

void CF1BookView::SetObjPatternStyle(short propVal)
{
	SetProperty(0x54a, VT_I2, propVal);
}

unsigned long CF1BookView::GetObjPatternFG()
{
	unsigned long result;
	GetProperty(0x54b, VT_I4, (void*)&result);
	return result;
}

void CF1BookView::SetObjPatternFG(unsigned long propVal)
{
	SetProperty(0x54b, VT_I4, propVal);
}

unsigned long CF1BookView::GetObjPatternBG()
{
	unsigned long result;
	GetProperty(0x54c, VT_I4, (void*)&result);
	return result;
}

void CF1BookView::SetObjPatternBG(unsigned long propVal)
{
	SetProperty(0x54c, VT_I4, propVal);
}

CString CF1BookView::GetDefaultFontName()
{
	CString result;
	GetProperty(0x551, VT_BSTR, (void*)&result);
	return result;
}

void CF1BookView::SetDefaultFontName(LPCTSTR propVal)
{
	SetProperty(0x551, VT_BSTR, propVal);
}

short CF1BookView::GetDefaultFontSize()
{
	short result;
	GetProperty(0x552, VT_I2, (void*)&result);
	return result;
}

void CF1BookView::SetDefaultFontSize(short propVal)
{
	SetProperty(0x552, VT_I2, propVal);
}

BOOL CF1BookView::GetSelHdrRow()
{
	BOOL result;
	GetProperty(0x553, VT_BOOL, (void*)&result);
	return result;
}

void CF1BookView::SetSelHdrRow(BOOL propVal)
{
	SetProperty(0x553, VT_BOOL, propVal);
}

BOOL CF1BookView::GetSelHdrCol()
{
	BOOL result;
	GetProperty(0x554, VT_BOOL, (void*)&result);
	return result;
}

void CF1BookView::SetSelHdrCol(BOOL propVal)
{
	SetProperty(0x554, VT_BOOL, propVal);
}

BOOL CF1BookView::GetSelHdrTopLeft()
{
	BOOL result;
	GetProperty(0x555, VT_BOOL, (void*)&result);
	return result;
}

void CF1BookView::SetSelHdrTopLeft(BOOL propVal)
{
	SetProperty(0x555, VT_BOOL, propVal);
}

BOOL CF1BookView::GetIterationEnabled()
{
	BOOL result;
	GetProperty(0x556, VT_BOOL, (void*)&result);
	return result;
}

void CF1BookView::SetIterationEnabled(BOOL propVal)
{
	SetProperty(0x556, VT_BOOL, propVal);
}

short CF1BookView::GetIterationMax()
{
	short result;
	GetProperty(0x557, VT_I2, (void*)&result);
	return result;
}

void CF1BookView::SetIterationMax(short propVal)
{
	SetProperty(0x557, VT_I2, propVal);
}

double CF1BookView::GetIterationMaxChange()
{
	double result;
	GetProperty(0x558, VT_R8, (void*)&result);
	return result;
}

void CF1BookView::SetIterationMaxChange(double propVal)
{
	SetProperty(0x558, VT_R8, propVal);
}

short CF1BookView::GetPrintScale()
{
	short result;
	GetProperty(0x56d, VT_I2, (void*)&result);
	return result;
}

void CF1BookView::SetPrintScale(short propVal)
{
	SetProperty(0x56d, VT_I2, propVal);
}

BOOL CF1BookView::GetPrintScaleFitToPage()
{
	BOOL result;
	GetProperty(0x56e, VT_BOOL, (void*)&result);
	return result;
}

void CF1BookView::SetPrintScaleFitToPage(BOOL propVal)
{
	SetProperty(0x56e, VT_BOOL, propVal);
}

long CF1BookView::GetPrintScaleFitVPages()
{
	long result;
	GetProperty(0x570, VT_I4, (void*)&result);
	return result;
}

void CF1BookView::SetPrintScaleFitVPages(long propVal)
{
	SetProperty(0x570, VT_I4, propVal);
}

long CF1BookView::GetPrintScaleFitHPages()
{
	long result;
	GetProperty(0x56f, VT_I4, (void*)&result);
	return result;
}

void CF1BookView::SetPrintScaleFitHPages(long propVal)
{
	SetProperty(0x56f, VT_I4, propVal);
}

short CF1BookView::GetLineStyle()
{
	short result;
	GetProperty(0x573, VT_I2, (void*)&result);
	return result;
}

void CF1BookView::SetLineStyle(short propVal)
{
	SetProperty(0x573, VT_I2, propVal);
}

unsigned long CF1BookView::GetLineColor()
{
	unsigned long result;
	GetProperty(0x574, VT_I4, (void*)&result);
	return result;
}

void CF1BookView::SetLineColor(unsigned long propVal)
{
	SetProperty(0x574, VT_I4, propVal);
}

short CF1BookView::GetLineWeight()
{
	short result;
	GetProperty(0x575, VT_I2, (void*)&result);
	return result;
}

void CF1BookView::SetLineWeight(short propVal)
{
	SetProperty(0x575, VT_I2, propVal);
}

CString CF1BookView::GetODBCSQLState()
{
	CString result;
	GetProperty(0x57b, VT_BSTR, (void*)&result);
	return result;
}

void CF1BookView::SetODBCSQLState(LPCTSTR propVal)
{
	SetProperty(0x57b, VT_BSTR, propVal);
}

long CF1BookView::GetODBCNativeError()
{
	long result;
	GetProperty(0x57c, VT_I4, (void*)&result);
	return result;
}

void CF1BookView::SetODBCNativeError(long propVal)
{
	SetProperty(0x57c, VT_I4, propVal);
}

CString CF1BookView::GetODBCErrorMsg()
{
	CString result;
	GetProperty(0x57d, VT_BSTR, (void*)&result);
	return result;
}

void CF1BookView::SetODBCErrorMsg(LPCTSTR propVal)
{
	SetProperty(0x57d, VT_BSTR, propVal);
}

BOOL CF1BookView::GetDataTransferHeadings()
{
	BOOL result;
	GetProperty(0x585, VT_BOOL, (void*)&result);
	return result;
}

void CF1BookView::SetDataTransferHeadings(BOOL propVal)
{
	SetProperty(0x585, VT_BOOL, propVal);
}

BOOL CF1BookView::GetCanEditPasteSpecial()
{
	BOOL result;
	GetProperty(0x58d, VT_BOOL, (void*)&result);
	return result;
}

void CF1BookView::SetCanEditPasteSpecial(BOOL propVal)
{
	SetProperty(0x58d, VT_BOOL, propVal);
}

BOOL CF1BookView::GetPrecisionAsDisplayed()
{
	BOOL result;
	GetProperty(0x593, VT_BOOL, (void*)&result);
	return result;
}

void CF1BookView::SetPrecisionAsDisplayed(BOOL propVal)
{
	SetProperty(0x593, VT_BOOL, propVal);
}

long CF1BookView::GetDefaultFontCharSet()
{
	long result;
	GetProperty(0x59c, VT_I4, (void*)&result);
	return result;
}

void CF1BookView::SetDefaultFontCharSet(long propVal)
{
	SetProperty(0x59c, VT_I4, propVal);
}

BOOL CF1BookView::GetWantAllWindowInfoChanges()
{
	BOOL result;
	GetProperty(0x5a0, VT_BOOL, (void*)&result);
	return result;
}

void CF1BookView::SetWantAllWindowInfoChanges(BOOL propVal)
{
	SetProperty(0x5a0, VT_BOOL, propVal);
}

/////////////////////////////////////////////////////////////////////////////
// CF1BookView operations

double CF1BookView::GetNumberRC(long nRow, long nCol)
{
	double result;
	static BYTE parms[] =
		VTS_I4 VTS_I4;
	InvokeHelper(0x117, DISPATCH_PROPERTYGET, VT_R8, (void*)&result, parms,
		nRow, nCol);
	return result;
}

void CF1BookView::SetNumberRC(long nRow, long nCol, double newValue)
{
	static BYTE parms[] =
		VTS_I4 VTS_I4 VTS_R8;
	InvokeHelper(0x117, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nRow, nCol, newValue);
}

CString CF1BookView::GetColText(long nCol)
{
	CString result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x110, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, parms,
		nCol);
	return result;
}

void CF1BookView::SetColText(long nCol, LPCTSTR lpszNewValue)
{
	static BYTE parms[] =
		VTS_I4 VTS_BSTR;
	InvokeHelper(0x110, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nCol, lpszNewValue);
}

CString CF1BookView::GetDefinedName(LPCTSTR Name)
{
	CString result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x111, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, parms,
		Name);
	return result;
}

void CF1BookView::SetDefinedName(LPCTSTR Name, LPCTSTR lpszNewValue)
{
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR;
	InvokeHelper(0x111, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 Name, lpszNewValue);
}

CString CF1BookView::GetEntryRC(long nRow, long nCol)
{
	CString result;
	static BYTE parms[] =
		VTS_I4 VTS_I4;
	InvokeHelper(0x112, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, parms,
		nRow, nCol);
	return result;
}

void CF1BookView::SetEntryRC(long nRow, long nCol, LPCTSTR lpszNewValue)
{
	static BYTE parms[] =
		VTS_I4 VTS_I4 VTS_BSTR;
	InvokeHelper(0x112, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nRow, nCol, lpszNewValue);
}

CString CF1BookView::GetFormattedTextRC(long nRow, long nCol)
{
	CString result;
	static BYTE parms[] =
		VTS_I4 VTS_I4;
	InvokeHelper(0x113, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, parms,
		nRow, nCol);
	return result;
}

CString CF1BookView::GetFormulaRC(long nRow, long nCol)
{
	CString result;
	static BYTE parms[] =
		VTS_I4 VTS_I4;
	InvokeHelper(0x114, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, parms,
		nRow, nCol);
	return result;
}

void CF1BookView::SetFormulaRC(long nRow, long nCol, LPCTSTR lpszNewValue)
{
	static BYTE parms[] =
		VTS_I4 VTS_I4 VTS_BSTR;
	InvokeHelper(0x114, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nRow, nCol, lpszNewValue);
}

long CF1BookView::GetLastColForRow(long nRow)
{
	long result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x115, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, parms,
		nRow);
	return result;
}

BOOL CF1BookView::GetLogicalRC(long nRow, long nCol)
{
	BOOL result;
	static BYTE parms[] =
		VTS_I4 VTS_I4;
	InvokeHelper(0x116, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, parms,
		nRow, nCol);
	return result;
}

void CF1BookView::SetLogicalRC(long nRow, long nCol, BOOL bNewValue)
{
	static BYTE parms[] =
		VTS_I4 VTS_I4 VTS_BOOL;
	InvokeHelper(0x116, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nRow, nCol, bNewValue);
}

CString CF1BookView::GetRowText(long nRow)
{
	CString result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x118, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, parms,
		nRow);
	return result;
}

void CF1BookView::SetRowText(long nRow, LPCTSTR lpszNewValue)
{
	static BYTE parms[] =
		VTS_I4 VTS_BSTR;
	InvokeHelper(0x118, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nRow, lpszNewValue);
}

CString CF1BookView::GetTextRC(long nRow, long nCol)
{
	CString result;
	static BYTE parms[] =
		VTS_I4 VTS_I4;
	InvokeHelper(0x119, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, parms,
		nRow, nCol);
	return result;
}

void CF1BookView::SetTextRC(long nRow, long nCol, LPCTSTR lpszNewValue)
{
	static BYTE parms[] =
		VTS_I4 VTS_I4 VTS_BSTR;
	InvokeHelper(0x119, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nRow, nCol, lpszNewValue);
}

short CF1BookView::GetTypeRC(long nRow, long nCol)
{
	short result;
	static BYTE parms[] =
		VTS_I4 VTS_I4;
	InvokeHelper(0x11a, DISPATCH_PROPERTYGET, VT_I2, (void*)&result, parms,
		nRow, nCol);
	return result;
}

long CF1BookView::GetObjCellType(long ObjID)
{
	long result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x559, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, parms,
		ObjID);
	return result;
}

void CF1BookView::SetObjCellType(long ObjID, long nNewValue)
{
	static BYTE parms[] =
		VTS_I4 VTS_I4;
	InvokeHelper(0x559, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 ObjID, nNewValue);
}

long CF1BookView::GetObjCellRow(long ObjID)
{
	long result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x55a, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, parms,
		ObjID);
	return result;
}

void CF1BookView::SetObjCellRow(long ObjID, long nNewValue)
{
	static BYTE parms[] =
		VTS_I4 VTS_I4;
	InvokeHelper(0x55a, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 ObjID, nNewValue);
}

long CF1BookView::GetObjCellCol(long ObjID)
{
	long result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x55b, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, parms,
		ObjID);
	return result;
}

void CF1BookView::SetObjCellCol(long ObjID, long nNewValue)
{
	static BYTE parms[] =
		VTS_I4 VTS_I4;
	InvokeHelper(0x55b, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 ObjID, nNewValue);
}

long CF1BookView::GetObjSelection(short nSelection)
{
	long result;
	static BYTE parms[] =
		VTS_I2;
	InvokeHelper(0x55c, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, parms,
		nSelection);
	return result;
}

void CF1BookView::EditPasteValues()
{
	InvokeHelper(0x71, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CF1BookView::GetAlignment(short* pHorizontal, BOOL* pWordWrap, short* pVertical, short* pOrientation)
{
	static BYTE parms[] =
		VTS_PI2 VTS_PBOOL VTS_PI2 VTS_PI2;
	InvokeHelper(0x72, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 pHorizontal, pWordWrap, pVertical, pOrientation);
}

void CF1BookView::GetBorder(short* pLeft, short* pRight, short* pTop, short* pBottom, short* pShade, long* pcrLeft, long* pcrRight, long* pcrTop, long* pcrBottom)
{
	static BYTE parms[] =
		VTS_PI2 VTS_PI2 VTS_PI2 VTS_PI2 VTS_PI2 VTS_PI4 VTS_PI4 VTS_PI4 VTS_PI4;
	InvokeHelper(0x73, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 pLeft, pRight, pTop, pBottom, pShade, pcrLeft, pcrRight, pcrTop, pcrBottom);
}

void CF1BookView::GetFont(BSTR* pName, short* pSize, BOOL* pBold, BOOL* pItalic, BOOL* pUnderline, BOOL* pStrikeout, long* pcrColor, BOOL* pOutline, BOOL* pShadow)
{
	static BYTE parms[] =
		VTS_PBSTR VTS_PI2 VTS_PBOOL VTS_PBOOL VTS_PBOOL VTS_PBOOL VTS_PI4 VTS_PBOOL VTS_PBOOL;
	InvokeHelper(0x74, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 pName, pSize, pBold, pItalic, pUnderline, pStrikeout, pcrColor, pOutline, pShadow);
}

void CF1BookView::GetLineStyle(short* pStyle, long* pcrColor, short* pWeight)
{
	static BYTE parms[] =
		VTS_PI2 VTS_PI4 VTS_PI2;
	InvokeHelper(0x75, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 pStyle, pcrColor, pWeight);
}

void CF1BookView::GetPattern(short* pPattern, long* pcrFG, long* pcrBG)
{
	static BYTE parms[] =
		VTS_PI2 VTS_PI4 VTS_PI4;
	InvokeHelper(0x76, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 pPattern, pcrFG, pcrBG);
}

void CF1BookView::GetProtection(BOOL* pLocked, BOOL* pHidden)
{
	static BYTE parms[] =
		VTS_PBOOL VTS_PBOOL;
	InvokeHelper(0x77, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 pLocked, pHidden);
}

void CF1BookView::GetTabbedText(long nR1, long nC1, long nR2, long nC2, BOOL bValuesOnly, long* phText)
{
	static BYTE parms[] =
		VTS_I4 VTS_I4 VTS_I4 VTS_I4 VTS_BOOL VTS_PI4;
	InvokeHelper(0x78, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 nR1, nC1, nR2, nC2, bValuesOnly, phText);
}

void CF1BookView::SetTabbedText(long nStartRow, long nStartCol, long* pRows, long* pCols, BOOL bValuesOnly, LPCTSTR pText)
{
	static BYTE parms[] =
		VTS_I4 VTS_I4 VTS_PI4 VTS_PI4 VTS_BOOL VTS_BSTR;
	InvokeHelper(0x79, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 nStartRow, nStartCol, pRows, pCols, bValuesOnly, pText);
}

void CF1BookView::AddColPageBreak(long nCol)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x7a, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 nCol);
}

void CF1BookView::AddPageBreak()
{
	InvokeHelper(0x7b, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CF1BookView::AddRowPageBreak(long nRow)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x7c, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 nRow);
}

void CF1BookView::AddSelection(long nRow1, long nCol1, long nRow2, long nCol2)
{
	static BYTE parms[] =
		VTS_I4 VTS_I4 VTS_I4 VTS_I4;
	InvokeHelper(0x7d, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 nRow1, nCol1, nRow2, nCol2);
}

void CF1BookView::Attach(LPCTSTR Title)
{
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x7e, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 Title);
}

void CF1BookView::AttachToSS(long hSrcSS)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x7f, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 hSrcSS);
}

void CF1BookView::CheckRecalc()
{
	InvokeHelper(0x82, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CF1BookView::ClearClipboard()
{
	InvokeHelper(0x83, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CF1BookView::ClearRange(long nRow1, long nCol1, long nRow2, long nCol2, long ClearType)
{
	static BYTE parms[] =
		VTS_I4 VTS_I4 VTS_I4 VTS_I4 VTS_I4;
	InvokeHelper(0x84, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 nRow1, nCol1, nRow2, nCol2, ClearType);
}

void CF1BookView::CopyAll(long hSrcSS)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x87, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 hSrcSS);
}

void CF1BookView::CopyRange(long nDstR1, long nDstC1, long nDstR2, long nDstC2, long hSrcSS, long nSrcR1, long nSrcC1, long nSrcR2, long nSrcC2)
{
	static BYTE parms[] =
		VTS_I4 VTS_I4 VTS_I4 VTS_I4 VTS_I4 VTS_I4 VTS_I4 VTS_I4 VTS_I4;
	InvokeHelper(0x88, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 nDstR1, nDstC1, nDstR2, nDstC2, hSrcSS, nSrcR1, nSrcC1, nSrcR2, nSrcC2);
}

void CF1BookView::DeleteDefinedName(LPCTSTR pName)
{
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x8a, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 pName);
}

void CF1BookView::DeleteRange(long nRow1, long nCol1, long nRow2, long nCol2, long ShiftType)
{
	static BYTE parms[] =
		VTS_I4 VTS_I4 VTS_I4 VTS_I4 VTS_I4;
	InvokeHelper(0x8b, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 nRow1, nCol1, nRow2, nCol2, ShiftType);
}

void CF1BookView::Draw(long hDC, long x, long y, long cx, long cy, long nRow, long nCol, long* pRows, long* pCols, long nFixedRow, long nFixedCol, long nFixedRows, long nFixedCols)
{
	static BYTE parms[] =
		VTS_I4 VTS_I4 VTS_I4 VTS_I4 VTS_I4 VTS_I4 VTS_I4 VTS_PI4 VTS_PI4 VTS_I4 VTS_I4 VTS_I4 VTS_I4;
	InvokeHelper(0x8c, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 hDC, x, y, cx, cy, nRow, nCol, pRows, pCols, nFixedRow, nFixedCol, nFixedRows, nFixedCols);
}

void CF1BookView::EditClear(long ClearType)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x8d, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 ClearType);
}

void CF1BookView::EditCopy()
{
	InvokeHelper(0x8e, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CF1BookView::EditCopyDown()
{
	InvokeHelper(0x8f, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CF1BookView::EditCopyRight()
{
	InvokeHelper(0x90, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CF1BookView::EditCut()
{
	InvokeHelper(0x91, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CF1BookView::EditDelete(long ShiftType)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x92, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 ShiftType);
}

void CF1BookView::EditInsert(long InsertType)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x93, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 InsertType);
}

void CF1BookView::EditPaste()
{
	InvokeHelper(0x94, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CF1BookView::FormatCurrency0()
{
	InvokeHelper(0x9b, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CF1BookView::FormatCurrency2()
{
	InvokeHelper(0x9c, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CF1BookView::FormatFixed()
{
	InvokeHelper(0x9e, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CF1BookView::FormatFixed2()
{
	InvokeHelper(0x9f, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CF1BookView::FormatFraction()
{
	InvokeHelper(0xa1, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CF1BookView::FormatGeneral()
{
	InvokeHelper(0xa2, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CF1BookView::FormatHmmampm()
{
	InvokeHelper(0xa3, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CF1BookView::FormatMdyy()
{
	InvokeHelper(0xa4, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CF1BookView::FormatPercent()
{
	InvokeHelper(0xa7, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CF1BookView::FormatScientific()
{
	InvokeHelper(0xa8, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CF1BookView::GetActiveCell(long* pRow, long* pCol)
{
	static BYTE parms[] =
		VTS_PI4 VTS_PI4;
	InvokeHelper(0xa9, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 pRow, pCol);
}

short CF1BookView::GetColWidth(long nCol)
{
	short result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x11b, DISPATCH_PROPERTYGET, VT_I2, (void*)&result, parms,
		nCol);
	return result;
}

short CF1BookView::GetRowHeight(long nRow)
{
	short result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x11c, DISPATCH_PROPERTYGET, VT_I2, (void*)&result, parms,
		nRow);
	return result;
}

void CF1BookView::GetDefaultFont(BSTR* pBuf, short* pSize)
{
	static BYTE parms[] =
		VTS_PBSTR VTS_PI2;
	InvokeHelper(0xaa, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 pBuf, pSize);
}

void CF1BookView::GetHdrSelection(BOOL* pTopLeftHdr, BOOL* pRowHdr, BOOL* pColHdr)
{
	static BYTE parms[] =
		VTS_PBOOL VTS_PBOOL VTS_PBOOL;
	InvokeHelper(0xab, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 pTopLeftHdr, pRowHdr, pColHdr);
}

void CF1BookView::GetIteration(BOOL* pIteration, short* pMaxIterations, double* pMaxChange)
{
	static BYTE parms[] =
		VTS_PBOOL VTS_PI2 VTS_PR8;
	InvokeHelper(0xac, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 pIteration, pMaxIterations, pMaxChange);
}

void CF1BookView::GetPrintScale(short* pScale, BOOL* pFitToPage, long* pVPages, long* pHPages)
{
	static BYTE parms[] =
		VTS_PI2 VTS_PBOOL VTS_PI4 VTS_PI4;
	InvokeHelper(0xad, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 pScale, pFitToPage, pVPages, pHPages);
}

void CF1BookView::GetSelection(short nSelection, long* pR1, long* pC1, long* pR2, long* pC2)
{
	static BYTE parms[] =
		VTS_I2 VTS_PI4 VTS_PI4 VTS_PI4 VTS_PI4;
	InvokeHelper(0xae, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 nSelection, pR1, pC1, pR2, pC2);
}

void CF1BookView::HeapMin()
{
	InvokeHelper(0xb0, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CF1BookView::InitTable()
{
	InvokeHelper(0xb1, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CF1BookView::InsertRange(long nRow1, long nCol1, long nRow2, long nCol2, long InsertType)
{
	static BYTE parms[] =
		VTS_I4 VTS_I4 VTS_I4 VTS_I4 VTS_I4;
	InvokeHelper(0xb2, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 nRow1, nCol1, nRow2, nCol2, InsertType);
}

void CF1BookView::MoveRange(long nRow1, long nCol1, long nRow2, long nCol2, long nRowOffset, long nColOffset)
{
	static BYTE parms[] =
		VTS_I4 VTS_I4 VTS_I4 VTS_I4 VTS_I4 VTS_I4;
	InvokeHelper(0xb4, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 nRow1, nCol1, nRow2, nCol2, nRowOffset, nColOffset);
}

void CF1BookView::ObjAddItem(long ObjID, LPCTSTR ItemText)
{
	static BYTE parms[] =
		VTS_I4 VTS_BSTR;
	InvokeHelper(0xb5, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 ObjID, ItemText);
}

void CF1BookView::ObjAddSelection(long ObjID)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0xb6, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 ObjID);
}

void CF1BookView::ObjBringToFront()
{
	InvokeHelper(0xb7, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CF1BookView::ObjDeleteItem(long ObjID, short nItem)
{
	static BYTE parms[] =
		VTS_I4 VTS_I2;
	InvokeHelper(0xb8, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 ObjID, nItem);
}

void CF1BookView::ObjGetCell(long ObjID, short* pControlCellType, long* pRow, long* pCol)
{
	static BYTE parms[] =
		VTS_I4 VTS_PI2 VTS_PI4 VTS_PI4;
	InvokeHelper(0xb9, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 ObjID, pControlCellType, pRow, pCol);
}

void CF1BookView::ObjGetPos(long ObjID, float* pX1, float* pY1, float* pX2, float* pY2)
{
	static BYTE parms[] =
		VTS_I4 VTS_PR4 VTS_PR4 VTS_PR4 VTS_PR4;
	InvokeHelper(0xba, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 ObjID, pX1, pY1, pX2, pY2);
}

void CF1BookView::ObjGetSelection(short nSelection, long* pID)
{
	static BYTE parms[] =
		VTS_I2 VTS_PI4;
	InvokeHelper(0xbb, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 nSelection, pID);
}

void CF1BookView::ObjInsertItem(long ObjID, short nItem, LPCTSTR ItemText)
{
	static BYTE parms[] =
		VTS_I4 VTS_I2 VTS_BSTR;
	InvokeHelper(0xbc, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 ObjID, nItem, ItemText);
}

void CF1BookView::ObjNew(short ObjType, float nX1, float nY1, float nX2, float nY2, long* pID)
{
	static BYTE parms[] =
		VTS_I2 VTS_R4 VTS_R4 VTS_R4 VTS_R4 VTS_PI4;
	InvokeHelper(0xbe, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 ObjType, nX1, nY1, nX2, nY2, pID);
}

void CF1BookView::ObjNewPicture(float nX1, float nY1, float nX2, float nY2, long* pID, long hMF, long nMapMode, long nWndExtentX, long nWndExtentY)
{
	static BYTE parms[] =
		VTS_R4 VTS_R4 VTS_R4 VTS_R4 VTS_PI4 VTS_I4 VTS_I4 VTS_I4 VTS_I4;
	InvokeHelper(0xbf, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 nX1, nY1, nX2, nY2, pID, hMF, nMapMode, nWndExtentX, nWndExtentY);
}

void CF1BookView::ObjPosToTwips(float nX1, float nY1, float nX2, float nY2, long* pX, long* pY, long* pCX, long* pCY, short* pShown)
{
	static BYTE parms[] =
		VTS_R4 VTS_R4 VTS_R4 VTS_R4 VTS_PI4 VTS_PI4 VTS_PI4 VTS_PI4 VTS_PI2;
	InvokeHelper(0xc1, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 nX1, nY1, nX2, nY2, pX, pY, pCX, pCY, pShown);
}

void CF1BookView::ObjSendToBack()
{
	InvokeHelper(0xc2, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CF1BookView::ObjSetCell(long ObjID, short CellType, long nRow, long nCol)
{
	static BYTE parms[] =
		VTS_I4 VTS_I2 VTS_I4 VTS_I4;
	InvokeHelper(0xc3, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 ObjID, CellType, nRow, nCol);
}

void CF1BookView::ObjSetPicture(long ObjID, long hMF, short nMapMode, long nWndExtentX, long nWndExtentY)
{
	static BYTE parms[] =
		VTS_I4 VTS_I4 VTS_I2 VTS_I4 VTS_I4;
	InvokeHelper(0xc4, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 ObjID, hMF, nMapMode, nWndExtentX, nWndExtentY);
}

void CF1BookView::ObjSetPos(long ObjID, float nX1, float nY1, float nX2, float nY2)
{
	static BYTE parms[] =
		VTS_I4 VTS_R4 VTS_R4 VTS_R4 VTS_R4;
	InvokeHelper(0xc5, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 ObjID, nX1, nY1, nX2, nY2);
}

void CF1BookView::ObjSetSelection(long ObjID)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0xc6, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 ObjID);
}

void CF1BookView::OpenFileDlg(LPCTSTR pTitle, long hWndParent, BSTR* pBuf)
{
	static BYTE parms[] =
		VTS_BSTR VTS_I4 VTS_PBSTR;
	InvokeHelper(0xc7, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 pTitle, hWndParent, pBuf);
}

void CF1BookView::RangeToTwips(long nRow1, long nCol1, long nRow2, long nCol2, long* pX, long* pY, long* pCX, long* pCY, short* pShown)
{
	static BYTE parms[] =
		VTS_I4 VTS_I4 VTS_I4 VTS_I4 VTS_PI4 VTS_PI4 VTS_PI4 VTS_PI4 VTS_PI2;
	InvokeHelper(0xc9, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 nRow1, nCol1, nRow2, nCol2, pX, pY, pCX, pCY, pShown);
}

void CF1BookView::Read(LPCTSTR pPathName, short* pFileType)
{
	static BYTE parms[] =
		VTS_BSTR VTS_PI2;
	InvokeHelper(0xca, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 pPathName, pFileType);
}

void CF1BookView::ReadFromBlob(long hBlob, short nReservedBytes)
{
	static BYTE parms[] =
		VTS_I4 VTS_I2;
	InvokeHelper(0xcb, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 hBlob, nReservedBytes);
}

void CF1BookView::Recalc()
{
	InvokeHelper(0xcc, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CF1BookView::RemoveColPageBreak(long nCol)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0xcd, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 nCol);
}

void CF1BookView::RemovePageBreak()
{
	InvokeHelper(0xce, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CF1BookView::RemoveRowPageBreak(long nRow)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0xcf, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 nRow);
}

void CF1BookView::SaveWindowInfo()
{
	InvokeHelper(0xd2, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CF1BookView::SetActiveCell(long nRow, long nCol)
{
	static BYTE parms[] =
		VTS_I4 VTS_I4;
	InvokeHelper(0xd3, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 nRow, nCol);
}

void CF1BookView::SetAlignment(short HAlign, BOOL bWordWrap, short VAlign, short nOrientation)
{
	static BYTE parms[] =
		VTS_I2 VTS_BOOL VTS_I2 VTS_I2;
	InvokeHelper(0xd4, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 HAlign, bWordWrap, VAlign, nOrientation);
}

void CF1BookView::SetBorder(short nOutline, short nLeft, short nRight, short nTop, short nBottom, short nShade, unsigned long crOutline, unsigned long crLeft, unsigned long crRight, unsigned long crTop, unsigned long crBottom)
{
	static BYTE parms[] =
		VTS_I2 VTS_I2 VTS_I2 VTS_I2 VTS_I2 VTS_I2 VTS_I4 VTS_I4 VTS_I4 VTS_I4 VTS_I4;
	InvokeHelper(0xd5, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 nOutline, nLeft, nRight, nTop, nBottom, nShade, crOutline, crLeft, crRight, crTop, crBottom);
}

void CF1BookView::SetColWidth(long nCol1, long nCol2, short nWidth, BOOL bDefColWidth)
{
	static BYTE parms[] =
		VTS_I4 VTS_I4 VTS_I2 VTS_BOOL;
	InvokeHelper(0xd6, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 nCol1, nCol2, nWidth, bDefColWidth);
}

void CF1BookView::SetColWidthAuto(long nRow1, long nCol1, long nRow2, long nCol2, BOOL bSetDefaults)
{
	static BYTE parms[] =
		VTS_I4 VTS_I4 VTS_I4 VTS_I4 VTS_BOOL;
	InvokeHelper(0xd7, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 nRow1, nCol1, nRow2, nCol2, bSetDefaults);
}

void CF1BookView::SetDefaultFont(LPCTSTR Name, short nSize)
{
	static BYTE parms[] =
		VTS_BSTR VTS_I2;
	InvokeHelper(0xd8, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 Name, nSize);
}

void CF1BookView::SetFont(LPCTSTR pName, short nSize, BOOL bBold, BOOL bItalic, BOOL bUnderline, BOOL bStrikeout, unsigned long crColor, BOOL bOutline, BOOL bShadow)
{
	static BYTE parms[] =
		VTS_BSTR VTS_I2 VTS_BOOL VTS_BOOL VTS_BOOL VTS_BOOL VTS_I4 VTS_BOOL VTS_BOOL;
	InvokeHelper(0xd9, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 pName, nSize, bBold, bItalic, bUnderline, bStrikeout, crColor, bOutline, bShadow);
}

void CF1BookView::SetHdrSelection(BOOL bTopLeftHdr, BOOL bRowHdr, BOOL bColHdr)
{
	static BYTE parms[] =
		VTS_BOOL VTS_BOOL VTS_BOOL;
	InvokeHelper(0xda, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 bTopLeftHdr, bRowHdr, bColHdr);
}

void CF1BookView::SetIteration(BOOL bIteration, short nMaxIterations, double nMaxChange)
{
	static BYTE parms[] =
		VTS_BOOL VTS_I2 VTS_R8;
	InvokeHelper(0xdb, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 bIteration, nMaxIterations, nMaxChange);
}

void CF1BookView::SetLineStyle(short nStyle, unsigned long crColor, short nWeight)
{
	static BYTE parms[] =
		VTS_I2 VTS_I4 VTS_I2;
	InvokeHelper(0xdc, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 nStyle, crColor, nWeight);
}

void CF1BookView::SetPattern(short nPattern, unsigned long crFG, unsigned long crBG)
{
	static BYTE parms[] =
		VTS_I2 VTS_I4 VTS_I4;
	InvokeHelper(0xdd, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 nPattern, crFG, crBG);
}

void CF1BookView::SetPrintAreaFromSelection()
{
	InvokeHelper(0xde, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CF1BookView::SetPrintScale(short nScale, BOOL bFitToPage, short nVPages, short nHPages)
{
	static BYTE parms[] =
		VTS_I2 VTS_BOOL VTS_I2 VTS_I2;
	InvokeHelper(0xdf, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 nScale, bFitToPage, nVPages, nHPages);
}

void CF1BookView::SetPrintTitlesFromSelection()
{
	InvokeHelper(0xe0, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CF1BookView::SetProtection(BOOL bLocked, BOOL bHidden)
{
	static BYTE parms[] =
		VTS_BOOL VTS_BOOL;
	InvokeHelper(0xe1, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 bLocked, bHidden);
}

void CF1BookView::SetRowHeight(long nRow1, long nRow2, short nHeight, BOOL bDefRowHeight)
{
	static BYTE parms[] =
		VTS_I4 VTS_I4 VTS_I2 VTS_BOOL;
	InvokeHelper(0xe2, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 nRow1, nRow2, nHeight, bDefRowHeight);
}

void CF1BookView::SetRowHeightAuto(long nRow1, long nCol1, long nRow2, long nCol2, BOOL bSetDefaults)
{
	static BYTE parms[] =
		VTS_I4 VTS_I4 VTS_I4 VTS_I4 VTS_BOOL;
	InvokeHelper(0xe3, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 nRow1, nCol1, nRow2, nCol2, bSetDefaults);
}

void CF1BookView::SetSelection(long nRow1, long nCol1, long nRow2, long nCol2)
{
	static BYTE parms[] =
		VTS_I4 VTS_I4 VTS_I4 VTS_I4;
	InvokeHelper(0xe4, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 nRow1, nCol1, nRow2, nCol2);
}

void CF1BookView::ShowActiveCell()
{
	InvokeHelper(0xe5, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CF1BookView::Sort3(long nRow1, long nCol1, long nRow2, long nCol2, BOOL bSortByRows, long nKey1, long nKey2, long nKey3)
{
	static BYTE parms[] =
		VTS_I4 VTS_I4 VTS_I4 VTS_I4 VTS_BOOL VTS_I4 VTS_I4 VTS_I4;
	InvokeHelper(0xe6, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 nRow1, nCol1, nRow2, nCol2, bSortByRows, nKey1, nKey2, nKey3);
}

void CF1BookView::SwapTables(long hSS2)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0xe9, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 hSS2);
}

void CF1BookView::TransactCommit()
{
	InvokeHelper(0xea, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CF1BookView::TransactRollback()
{
	InvokeHelper(0xeb, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CF1BookView::TransactStart()
{
	InvokeHelper(0xec, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CF1BookView::TwipsToRC(long x, long y, long* pRow, long* pCol)
{
	static BYTE parms[] =
		VTS_I4 VTS_I4 VTS_PI4 VTS_PI4;
	InvokeHelper(0xed, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 x, y, pRow, pCol);
}

void CF1BookView::SSUpdate()
{
	InvokeHelper(0xee, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

short CF1BookView::SSVersion()
{
	short result;
	InvokeHelper(0xef, DISPATCH_METHOD, VT_I2, (void*)&result, NULL);
	return result;
}

void CF1BookView::Write(LPCTSTR PathName, short FileType)
{
	static BYTE parms[] =
		VTS_BSTR VTS_I2;
	InvokeHelper(0xf0, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 PathName, FileType);
}

void CF1BookView::WriteToBlob(long* phBlob, short nReservedBytes)
{
	static BYTE parms[] =
		VTS_PI4 VTS_I2;
	InvokeHelper(0xf1, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 phBlob, nReservedBytes);
}

void CF1BookView::SetRowHidden(long nRow1, long nRow2, BOOL bHidden)
{
	static BYTE parms[] =
		VTS_I4 VTS_I4 VTS_BOOL;
	InvokeHelper(0xf2, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 nRow1, nRow2, bHidden);
}

void CF1BookView::SetColHidden(long nCol1, long nCol2, BOOL bHidden)
{
	static BYTE parms[] =
		VTS_I4 VTS_I4 VTS_BOOL;
	InvokeHelper(0xf3, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 nCol1, nCol2, bHidden);
}

void CF1BookView::SetColWidthTwips(long nCol1, long nCol2, short nWidth, BOOL bDefColWidth)
{
	static BYTE parms[] =
		VTS_I4 VTS_I4 VTS_I2 VTS_BOOL;
	InvokeHelper(0xf4, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 nCol1, nCol2, nWidth, bDefColWidth);
}

CString CF1BookView::GetDefinedNameByIndex(short nName)
{
	CString result;
	static BYTE parms[] =
		VTS_I2;
	InvokeHelper(0x11d, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, parms,
		nName);
	return result;
}

CString CF1BookView::GetSheetName(short nSheet)
{
	CString result;
	static BYTE parms[] =
		VTS_I2;
	InvokeHelper(0x11e, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, parms,
		nSheet);
	return result;
}

void CF1BookView::SetSheetName(short nSheet, LPCTSTR lpszNewValue)
{
	static BYTE parms[] =
		VTS_I2 VTS_BSTR;
	InvokeHelper(0x11e, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nSheet, lpszNewValue);
}

unsigned long CF1BookView::GetPaletteEntry(long nEntry)
{
	unsigned long result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x11f, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, parms,
		nEntry);
	return result;
}

void CF1BookView::SetPaletteEntry(long nEntry, unsigned long newValue)
{
	static BYTE parms[] =
		VTS_I4 VTS_I4;
	InvokeHelper(0x11f, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nEntry, newValue);
}

void CF1BookView::EditInsertSheets()
{
	InvokeHelper(0xf5, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CF1BookView::EditDeleteSheets()
{
	InvokeHelper(0xf6, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CF1BookView::InsertSheets(long nSheet, long nSheets)
{
	static BYTE parms[] =
		VTS_I4 VTS_I4;
	InvokeHelper(0xf7, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 nSheet, nSheets);
}

void CF1BookView::DeleteSheets(long nSheet, long nSheets)
{
	static BYTE parms[] =
		VTS_I4 VTS_I4;
	InvokeHelper(0xf8, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 nSheet, nSheets);
}

short CF1BookView::GetColWidthTwips(long nCol)
{
	short result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x120, DISPATCH_PROPERTYGET, VT_I2, (void*)&result, parms,
		nCol);
	return result;
}

void CF1BookView::SetColWidthTwips(long nCol, short nNewValue)
{
	static BYTE parms[] =
		VTS_I4 VTS_I2;
	InvokeHelper(0x120, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nCol, nNewValue);
}

long CF1BookView::NextColPageBreak(long Col)
{
	long result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0xf9, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		Col);
	return result;
}

long CF1BookView::NextRowPageBreak(long Row)
{
	long result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0xfa, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		Row);
	return result;
}

long CF1BookView::ObjFirstID()
{
	long result;
	InvokeHelper(0xfb, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

long CF1BookView::ObjNextID(long ObjID)
{
	long result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0xfc, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		ObjID);
	return result;
}

short CF1BookView::ObjGetItemCount(long ObjID)
{
	short result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0xfd, DISPATCH_METHOD, VT_I2, (void*)&result, parms,
		ObjID);
	return result;
}

long CF1BookView::ObjGetType(long ObjID)
{
	long result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0xfe, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		ObjID);
	return result;
}

short CF1BookView::ObjGetSelectionCount()
{
	short result;
	InvokeHelper(0xff, DISPATCH_METHOD, VT_I2, (void*)&result, NULL);
	return result;
}

CString CF1BookView::FormatRCNr(long Row, long Col, BOOL DoAbsolute)
{
	CString result;
	static BYTE parms[] =
		VTS_I4 VTS_I4 VTS_BOOL;
	InvokeHelper(0x100, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		Row, Col, DoAbsolute);
	return result;
}

long CF1BookView::SS()
{
	long result;
	InvokeHelper(0x101, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

CString CF1BookView::GetObjItem(long ObjID, short nItem)
{
	CString result;
	static BYTE parms[] =
		VTS_I4 VTS_I2;
	InvokeHelper(0x121, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, parms,
		ObjID, nItem);
	return result;
}

void CF1BookView::SetObjItem(long ObjID, short nItem, LPCTSTR lpszNewValue)
{
	static BYTE parms[] =
		VTS_I4 VTS_I2 VTS_BSTR;
	InvokeHelper(0x121, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 ObjID, nItem, lpszNewValue);
}

CString CF1BookView::GetObjItems(long ObjID)
{
	CString result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x122, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, parms,
		ObjID);
	return result;
}

void CF1BookView::SetObjItems(long ObjID, LPCTSTR lpszNewValue)
{
	static BYTE parms[] =
		VTS_I4 VTS_BSTR;
	InvokeHelper(0x122, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 ObjID, lpszNewValue);
}

CString CF1BookView::GetObjName(long ObjID)
{
	CString result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x123, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, parms,
		ObjID);
	return result;
}

void CF1BookView::SetObjName(long ObjID, LPCTSTR lpszNewValue)
{
	static BYTE parms[] =
		VTS_I4 VTS_BSTR;
	InvokeHelper(0x123, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 ObjID, lpszNewValue);
}

CString CF1BookView::GetObjText(long ObjID)
{
	CString result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x124, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, parms,
		ObjID);
	return result;
}

void CF1BookView::SetObjText(long ObjID, LPCTSTR lpszNewValue)
{
	static BYTE parms[] =
		VTS_I4 VTS_BSTR;
	InvokeHelper(0x124, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 ObjID, lpszNewValue);
}

short CF1BookView::GetObjValue(long ObjID)
{
	short result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x125, DISPATCH_PROPERTYGET, VT_I2, (void*)&result, parms,
		ObjID);
	return result;
}

void CF1BookView::SetObjValue(long ObjID, short nNewValue)
{
	static BYTE parms[] =
		VTS_I4 VTS_I2;
	InvokeHelper(0x125, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 ObjID, nNewValue);
}

BOOL CF1BookView::GetObjVisible(long ObjID)
{
	BOOL result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x126, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, parms,
		ObjID);
	return result;
}

void CF1BookView::SetObjVisible(long ObjID, BOOL bNewValue)
{
	static BYTE parms[] =
		VTS_I4 VTS_BOOL;
	InvokeHelper(0x126, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 ObjID, bNewValue);
}

long CF1BookView::ObjNameToID(LPCTSTR Name)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x103, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		Name);
	return result;
}

long CF1BookView::DefinedNameCount()
{
	long result;
	InvokeHelper(0x104, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

CString CF1BookView::GetAutoFillItems(short nIndex)
{
	CString result;
	static BYTE parms[] =
		VTS_I2;
	InvokeHelper(0x127, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, parms,
		nIndex);
	return result;
}

void CF1BookView::SetAutoFillItems(short nIndex, LPCTSTR lpszNewValue)
{
	static BYTE parms[] =
		VTS_I2 VTS_BSTR;
	InvokeHelper(0x127, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nIndex, lpszNewValue);
}

void CF1BookView::SetValidationRule(LPCTSTR Rule, LPCTSTR Text)
{
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR;
	InvokeHelper(0x106, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 Rule, Text);
}

void CF1BookView::GetValidationRule(BSTR* Rule, BSTR* Text)
{
	static BYTE parms[] =
		VTS_PBSTR VTS_PBSTR;
	InvokeHelper(0x107, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 Rule, Text);
}

short CF1BookView::AutoFillItemsCount()
{
	short result;
	InvokeHelper(0x108, DISPATCH_METHOD, VT_I2, (void*)&result, NULL);
	return result;
}

void CF1BookView::CopyRangeEx(long nDstSheet, long nDstR1, long nDstC1, long nDstR2, long nDstC2, long hSrcSS, long nSrcSheet, long nSrcR1, long nSrcC1, long nSrcR2, long nSrcC2)
{
	static BYTE parms[] =
		VTS_I4 VTS_I4 VTS_I4 VTS_I4 VTS_I4 VTS_I4 VTS_I4 VTS_I4 VTS_I4 VTS_I4 VTS_I4;
	InvokeHelper(0x109, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 nDstSheet, nDstR1, nDstC1, nDstR2, nDstC2, hSrcSS, nSrcSheet, nSrcR1, nSrcC1, nSrcR2, nSrcC2);
}

void CF1BookView::Sort(long nR1, long nC1, long nR2, long nC2, BOOL bSortByRows, const VARIANT& Keys)
{
	static BYTE parms[] =
		VTS_I4 VTS_I4 VTS_I4 VTS_I4 VTS_BOOL VTS_VARIANT;
	InvokeHelper(0x10a, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 nR1, nC1, nR2, nC2, bSortByRows, &Keys);
}

BOOL CF1BookView::GetColHidden(long nCol)
{
	BOOL result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x128, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, parms,
		nCol);
	return result;
}

void CF1BookView::SetColHidden(long nCol, BOOL bNewValue)
{
	static BYTE parms[] =
		VTS_I4 VTS_BOOL;
	InvokeHelper(0x128, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nCol, bNewValue);
}

BOOL CF1BookView::GetRowHidden(long nRow)
{
	BOOL result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x129, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, parms,
		nRow);
	return result;
}

void CF1BookView::SetRowHidden(long nRow, BOOL bNewValue)
{
	static BYTE parms[] =
		VTS_I4 VTS_BOOL;
	InvokeHelper(0x129, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nRow, bNewValue);
}

void CF1BookView::DeleteAutoFillItems(short nIndex)
{
	static BYTE parms[] =
		VTS_I2;
	InvokeHelper(0x10b, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 nIndex);
}

void CF1BookView::ODBCConnect(BSTR* pConnect, BOOL bShowErrors, short* pRetCode)
{
	static BYTE parms[] =
		VTS_PBSTR VTS_BOOL VTS_PI2;
	InvokeHelper(0x10c, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 pConnect, bShowErrors, pRetCode);
}

void CF1BookView::ODBCDisconnect()
{
	InvokeHelper(0x10d, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CF1BookView::ODBCQuery(BSTR* pQuery, long nRow, long nCol, BOOL bForceShowDlg, BOOL* pSetColNames, BOOL* pSetColFormats, BOOL* pSetColWidths, BOOL* pSetMaxRC, short* pRetCode)
{
	static BYTE parms[] =
		VTS_PBSTR VTS_I4 VTS_I4 VTS_BOOL VTS_PBOOL VTS_PBOOL VTS_PBOOL VTS_PBOOL VTS_PI2;
	InvokeHelper(0x10e, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 pQuery, nRow, nCol, bForceShowDlg, pSetColNames, pSetColFormats, pSetColWidths, pSetMaxRC, pRetCode);
}

BOOL CF1BookView::GetSheetSelected(long nSheet)
{
	BOOL result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x12a, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, parms,
		nSheet);
	return result;
}

void CF1BookView::SetSheetSelected(long nSheet, BOOL bNewValue)
{
	static BYTE parms[] =
		VTS_I4 VTS_BOOL;
	InvokeHelper(0x12a, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nSheet, bNewValue);
}

void CF1BookView::PrintPreviewDC(long hDC, short nPage, short* pPages)
{
	static BYTE parms[] =
		VTS_I4 VTS_I2 VTS_PI2;
	InvokeHelper(0x521, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 hDC, nPage, pPages);
}

void CF1BookView::PrintPreview(long hWnd, long x, long y, long cx, long cy, short nPage, short* pPages)
{
	static BYTE parms[] =
		VTS_I4 VTS_I4 VTS_I4 VTS_I4 VTS_I4 VTS_I2 VTS_PI2;
	InvokeHelper(0x522, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 hWnd, x, y, cx, cy, nPage, pPages);
}

CString CF1BookView::GetEntrySRC(long nSheet, long nRow, long nCol)
{
	CString result;
	static BYTE parms[] =
		VTS_I4 VTS_I4 VTS_I4;
	InvokeHelper(0x523, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, parms,
		nSheet, nRow, nCol);
	return result;
}

void CF1BookView::SetEntrySRC(long nSheet, long nRow, long nCol, LPCTSTR lpszNewValue)
{
	static BYTE parms[] =
		VTS_I4 VTS_I4 VTS_I4 VTS_BSTR;
	InvokeHelper(0x523, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nSheet, nRow, nCol, lpszNewValue);
}

CString CF1BookView::GetFormattedTextSRC(long nSheet, long nRow, long nCol)
{
	CString result;
	static BYTE parms[] =
		VTS_I4 VTS_I4 VTS_I4;
	InvokeHelper(0x524, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, parms,
		nSheet, nRow, nCol);
	return result;
}

CString CF1BookView::GetFormulaSRC(long nSheet, long nRow, long nCol)
{
	CString result;
	static BYTE parms[] =
		VTS_I4 VTS_I4 VTS_I4;
	InvokeHelper(0x525, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, parms,
		nSheet, nRow, nCol);
	return result;
}

void CF1BookView::SetFormulaSRC(long nSheet, long nRow, long nCol, LPCTSTR lpszNewValue)
{
	static BYTE parms[] =
		VTS_I4 VTS_I4 VTS_I4 VTS_BSTR;
	InvokeHelper(0x525, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nSheet, nRow, nCol, lpszNewValue);
}

BOOL CF1BookView::GetLogicalSRC(long nSheet, long nRow, long nCol)
{
	BOOL result;
	static BYTE parms[] =
		VTS_I4 VTS_I4 VTS_I4;
	InvokeHelper(0x526, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, parms,
		nSheet, nRow, nCol);
	return result;
}

void CF1BookView::SetLogicalSRC(long nSheet, long nRow, long nCol, BOOL bNewValue)
{
	static BYTE parms[] =
		VTS_I4 VTS_I4 VTS_I4 VTS_BOOL;
	InvokeHelper(0x526, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nSheet, nRow, nCol, bNewValue);
}

double CF1BookView::GetNumberSRC(long nSheet, long nRow, long nCol)
{
	double result;
	static BYTE parms[] =
		VTS_I4 VTS_I4 VTS_I4;
	InvokeHelper(0x527, DISPATCH_PROPERTYGET, VT_R8, (void*)&result, parms,
		nSheet, nRow, nCol);
	return result;
}

void CF1BookView::SetNumberSRC(long nSheet, long nRow, long nCol, double newValue)
{
	static BYTE parms[] =
		VTS_I4 VTS_I4 VTS_I4 VTS_R8;
	InvokeHelper(0x527, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nSheet, nRow, nCol, newValue);
}

CString CF1BookView::GetTextSRC(long nSheet, long nRow, long nCol)
{
	CString result;
	static BYTE parms[] =
		VTS_I4 VTS_I4 VTS_I4;
	InvokeHelper(0x528, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, parms,
		nSheet, nRow, nCol);
	return result;
}

void CF1BookView::SetTextSRC(long nSheet, long nRow, long nCol, LPCTSTR lpszNewValue)
{
	static BYTE parms[] =
		VTS_I4 VTS_I4 VTS_I4 VTS_BSTR;
	InvokeHelper(0x528, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nSheet, nRow, nCol, lpszNewValue);
}

short CF1BookView::GetTypeSRC(long nSheet, long nRow, long nCol)
{
	short result;
	static BYTE parms[] =
		VTS_I4 VTS_I4 VTS_I4;
	InvokeHelper(0x529, DISPATCH_PROPERTYGET, VT_I2, (void*)&result, parms,
		nSheet, nRow, nCol);
	return result;
}

void CF1BookView::WriteRange(long nSheet, long nRow1, long nCol1, long nRow2, long nCol2, LPCTSTR pPathName, short FileType)
{
	static BYTE parms[] =
		VTS_I4 VTS_I4 VTS_I4 VTS_I4 VTS_I4 VTS_BSTR VTS_I2;
	InvokeHelper(0x52a, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 nSheet, nRow1, nCol1, nRow2, nCol2, pPathName, FileType);
}

void CF1BookView::InsertHTML(long nSheet, long nRow1, long nCol1, long nRow2, long nCol2, LPCTSTR pPathName, BOOL bDataOnly, LPCTSTR pAnchorName)
{
	static BYTE parms[] =
		VTS_I4 VTS_I4 VTS_I4 VTS_I4 VTS_I4 VTS_BSTR VTS_BOOL VTS_BSTR;
	InvokeHelper(0x52b, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 nSheet, nRow1, nCol1, nRow2, nCol2, pPathName, bDataOnly, pAnchorName);
}

CString CF1BookView::GetFormulaLocalRC(long nRow, long nCol)
{
	CString result;
	static BYTE parms[] =
		VTS_I4 VTS_I4;
	InvokeHelper(0x52f, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, parms,
		nRow, nCol);
	return result;
}

void CF1BookView::SetFormulaLocalRC(long nRow, long nCol, LPCTSTR lpszNewValue)
{
	static BYTE parms[] =
		VTS_I4 VTS_I4 VTS_BSTR;
	InvokeHelper(0x52f, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nRow, nCol, lpszNewValue);
}

CString CF1BookView::GetFormulaLocalSRC(long nSheet, long nRow, long nCol)
{
	CString result;
	static BYTE parms[] =
		VTS_I4 VTS_I4 VTS_I4;
	InvokeHelper(0x530, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, parms,
		nSheet, nRow, nCol);
	return result;
}

void CF1BookView::SetFormulaLocalSRC(long nSheet, long nRow, long nCol, LPCTSTR lpszNewValue)
{
	static BYTE parms[] =
		VTS_I4 VTS_I4 VTS_I4 VTS_BSTR;
	InvokeHelper(0x530, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nSheet, nRow, nCol, lpszNewValue);
}

CString CF1BookView::GetDefinedNameLocal(LPCTSTR Name)
{
	CString result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x531, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, parms,
		Name);
	return result;
}

void CF1BookView::SetDefinedNameLocal(LPCTSTR Name, LPCTSTR lpszNewValue)
{
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR;
	InvokeHelper(0x531, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 Name, lpszNewValue);
}

void CF1BookView::CopyDataFromArray(long nSheet, long nRow1, long nCol1, long nRow2, long nCol2, BOOL bValuesOnly, const VARIANT& Array)
{
	static BYTE parms[] =
		VTS_I4 VTS_I4 VTS_I4 VTS_I4 VTS_I4 VTS_BOOL VTS_VARIANT;
	InvokeHelper(0x534, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 nSheet, nRow1, nCol1, nRow2, nCol2, bValuesOnly, &Array);
}

void CF1BookView::CopyDataToArray(long nSheet, long nRow1, long nCol1, long nRow2, long nCol2, BOOL bValuesOnly, const VARIANT& Array)
{
	static BYTE parms[] =
		VTS_I4 VTS_I4 VTS_I4 VTS_I4 VTS_I4 VTS_BOOL VTS_VARIANT;
	InvokeHelper(0x535, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 nSheet, nRow1, nCol1, nRow2, nCol2, bValuesOnly, &Array);
}

void CF1BookView::ODBCError(BSTR* pSQLState, long* pNativeError, BSTR* pErrorMsg)
{
	static BYTE parms[] =
		VTS_PBSTR VTS_PI4 VTS_PBSTR;
	InvokeHelper(0x53b, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 pSQLState, pNativeError, pErrorMsg);
}

void CF1BookView::ODBCPrepare(LPCTSTR SQLStr, short* pRetCode)
{
	static BYTE parms[] =
		VTS_BSTR VTS_PI2;
	InvokeHelper(0x53c, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 SQLStr, pRetCode);
}

void CF1BookView::ODBCBindParameter(long nParam, long nCol, short CDataType, short* pRetCode)
{
	static BYTE parms[] =
		VTS_I4 VTS_I4 VTS_I2 VTS_PI2;
	InvokeHelper(0x53d, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 nParam, nCol, CDataType, pRetCode);
}

void CF1BookView::ODBCExecute(long nRow1, long nRow2, short* pRetCode)
{
	static BYTE parms[] =
		VTS_I4 VTS_I4 VTS_PI2;
	InvokeHelper(0x53e, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 nRow1, nRow2, pRetCode);
}

void CF1BookView::ObjNewPolygon(float X1, float Y1, float X2, float Y2, long* pID, const VARIANT& ArrayX, const VARIANT& ArrayY, BOOL bClosed)
{
	static BYTE parms[] =
		VTS_R4 VTS_R4 VTS_R4 VTS_R4 VTS_PI4 VTS_VARIANT VTS_VARIANT VTS_BOOL;
	InvokeHelper(0x541, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 X1, Y1, X2, Y2, pID, &ArrayX, &ArrayY, bClosed);
}

void CF1BookView::ObjSetPolygonPoints(long nID, const VARIANT& ArrayX, const VARIANT& ArrayY, BOOL bClosed)
{
	static BYTE parms[] =
		VTS_I4 VTS_VARIANT VTS_VARIANT VTS_BOOL;
	InvokeHelper(0x542, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 nID, &ArrayX, &ArrayY, bClosed);
}

CString CF1BookView::GetTabbedTextEx(long nR1, long nC1, long nR2, long nC2, BOOL bValuesOnly)
{
	CString result;
	static BYTE parms[] =
		VTS_I4 VTS_I4 VTS_I4 VTS_I4 VTS_BOOL;
	InvokeHelper(0x54f, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		nR1, nC1, nR2, nC2, bValuesOnly);
	return result;
}

CF1RangeRef CF1BookView::SetTabbedTextEx(long nStartRow, long nStartCol, BOOL bValuesOnly, LPCTSTR pText)
{
	LPDISPATCH pDispatch;
	static BYTE parms[] =
		VTS_I4 VTS_I4 VTS_BOOL VTS_BSTR;
	InvokeHelper(0x550, DISPATCH_METHOD, VT_DISPATCH, (void*)&pDispatch, parms,
		nStartRow, nStartCol, bValuesOnly, pText);
	return CF1RangeRef(pDispatch);
}

long CF1BookView::ObjCreate(long ObjType, float nX1, float nY1, float nX2, float nY2)
{
	long result;
	static BYTE parms[] =
		VTS_I4 VTS_R4 VTS_R4 VTS_R4 VTS_R4;
	InvokeHelper(0x55d, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		ObjType, nX1, nY1, nX2, nY2);
	return result;
}

long CF1BookView::ObjCreatePicture(float nX1, float nY1, float nX2, float nY2, long hMF, long nMapMode, long nWndExtentX, long nWndExtentY)
{
	long result;
	static BYTE parms[] =
		VTS_R4 VTS_R4 VTS_R4 VTS_R4 VTS_I4 VTS_I4 VTS_I4 VTS_I4;
	InvokeHelper(0x55e, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		nX1, nY1, nX2, nY2, hMF, nMapMode, nWndExtentX, nWndExtentY);
	return result;
}

long CF1BookView::ReadEx(LPCTSTR pPathName)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x55f, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		pPathName);
	return result;
}

long CF1BookView::WriteToBlobEx(short nReservedBytes)
{
	long result;
	static BYTE parms[] =
		VTS_I2;
	InvokeHelper(0x560, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		nReservedBytes);
	return result;
}

long CF1BookView::ObjCreatePolygon(float X1, float Y1, float X2, float Y2, const VARIANT& ArrayX, const VARIANT& ArrayY, BOOL bClosed)
{
	long result;
	static BYTE parms[] =
		VTS_R4 VTS_R4 VTS_R4 VTS_R4 VTS_VARIANT VTS_VARIANT VTS_BOOL;
	InvokeHelper(0x561, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		X1, Y1, X2, Y2, &ArrayX, &ArrayY, bClosed);
	return result;
}

CF1ObjPos CF1BookView::ObjGetPosEx(long ObjID)
{
	LPDISPATCH pDispatch;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x562, DISPATCH_METHOD, VT_DISPATCH, (void*)&pDispatch, parms,
		ObjID);
	return CF1ObjPos(pDispatch);
}

short CF1BookView::ObjPosShown(float X1, float Y1, float X2, float Y2)
{
	short result;
	static BYTE parms[] =
		VTS_R4 VTS_R4 VTS_R4 VTS_R4;
	InvokeHelper(0x563, DISPATCH_METHOD, VT_I2, (void*)&result, parms,
		X1, Y1, X2, Y2);
	return result;
}

CF1RangeRef CF1BookView::GetSelectionEx(short nSelection)
{
	LPDISPATCH pDispatch;
	static BYTE parms[] =
		VTS_I2;
	InvokeHelper(0x564, DISPATCH_PROPERTYGET, VT_DISPATCH, (void*)&pDispatch, parms,
		nSelection);
	return CF1RangeRef(pDispatch);
}

CF1Rect CF1BookView::ObjPosToTwipsEx(float X1, float Y1, float X2, float Y2)
{
	LPDISPATCH pDispatch;
	static BYTE parms[] =
		VTS_R4 VTS_R4 VTS_R4 VTS_R4;
	InvokeHelper(0x565, DISPATCH_METHOD, VT_DISPATCH, (void*)&pDispatch, parms,
		X1, Y1, X2, Y2);
	return CF1Rect(pDispatch);
}

CF1Rect CF1BookView::RangeToTwipsEx(long nRow1, long nCol1, long nRow2, long nCol2)
{
	LPDISPATCH pDispatch;
	static BYTE parms[] =
		VTS_I4 VTS_I4 VTS_I4 VTS_I4;
	InvokeHelper(0x566, DISPATCH_METHOD, VT_DISPATCH, (void*)&pDispatch, parms,
		nRow1, nCol1, nRow2, nCol2);
	return CF1Rect(pDispatch);
}

short CF1BookView::RangeShown(long nR1, long nC1, long nR2, long nC2)
{
	short result;
	static BYTE parms[] =
		VTS_I4 VTS_I4 VTS_I4 VTS_I4;
	InvokeHelper(0x567, DISPATCH_METHOD, VT_I2, (void*)&result, parms,
		nR1, nC1, nR2, nC2);
	return result;
}

long CF1BookView::TwipsToRow(long nTwips)
{
	long result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x568, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		nTwips);
	return result;
}

long CF1BookView::TwipsToCol(long nTwips)
{
	long result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x569, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		nTwips);
	return result;
}

short CF1BookView::PrintPreviewDCEx(long hDC, short nPage)
{
	short result;
	static BYTE parms[] =
		VTS_I4 VTS_I2;
	InvokeHelper(0x56a, DISPATCH_METHOD, VT_I2, (void*)&result, parms,
		hDC, nPage);
	return result;
}

short CF1BookView::PrintPreviewEx(long hWnd, long x, long y, long cx, long cy, short nPage)
{
	short result;
	static BYTE parms[] =
		VTS_I4 VTS_I4 VTS_I4 VTS_I4 VTS_I4 VTS_I2;
	InvokeHelper(0x56b, DISPATCH_METHOD, VT_I2, (void*)&result, parms,
		hWnd, x, y, cx, cy, nPage);
	return result;
}

void CF1BookView::ODBCConnectEx(LPDISPATCH pConnectObj, BOOL bShowErrors)
{
	static BYTE parms[] =
		VTS_DISPATCH VTS_BOOL;
	InvokeHelper(0x579, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 pConnectObj, bShowErrors);
}

void CF1BookView::ODBCQueryEx(LPDISPATCH pQueryObj, long nRow, long nCol, BOOL bForceShowDlg)
{
	static BYTE parms[] =
		VTS_DISPATCH VTS_I4 VTS_I4 VTS_BOOL;
	InvokeHelper(0x57a, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 pQueryObj, nRow, nCol, bForceShowDlg);
}

short CF1BookView::ODBCPrepareEx(LPCTSTR SQLStr)
{
	short result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x57e, DISPATCH_METHOD, VT_I2, (void*)&result, parms,
		SQLStr);
	return result;
}

short CF1BookView::ODBCBindParameterEx(long nParam, long nCol, long CDataType)
{
	short result;
	static BYTE parms[] =
		VTS_I4 VTS_I4 VTS_I4;
	InvokeHelper(0x57f, DISPATCH_METHOD, VT_I2, (void*)&result, parms,
		nParam, nCol, CDataType);
	return result;
}

short CF1BookView::ODBCExecuteEx(long nRow1, long nRow2)
{
	short result;
	static BYTE parms[] =
		VTS_I4 VTS_I4;
	InvokeHelper(0x580, DISPATCH_METHOD, VT_I2, (void*)&result, parms,
		nRow1, nRow2);
	return result;
}

CString CF1BookView::OpenFileDlgEx(LPCTSTR pTitle, long hWndParent)
{
	CString result;
	static BYTE parms[] =
		VTS_BSTR VTS_I4;
	InvokeHelper(0x586, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		pTitle, hWndParent);
	return result;
}

CF1BookView CF1BookView::CreateBookView()
{
	LPDISPATCH pDispatch;
	InvokeHelper(0x588, DISPATCH_METHOD, VT_DISPATCH, (void*)&pDispatch, NULL);
	return CF1BookView(pDispatch);
}

void CF1BookView::EditPasteSpecial(long PasteWhat, long PasteOp)
{
	static BYTE parms[] =
		VTS_I4 VTS_I4;
	InvokeHelper(0x58e, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 PasteWhat, PasteOp);
}

CF1NumberFormat CF1BookView::GetFirstNumberFormat()
{
	LPDISPATCH pDispatch;
	InvokeHelper(0x590, DISPATCH_METHOD, VT_DISPATCH, (void*)&pDispatch, NULL);
	return CF1NumberFormat(pDispatch);
}

void CF1BookView::GetNextNumberFormat(LPDISPATCH pNumberFormat)
{
	static BYTE parms[] =
		VTS_DISPATCH;
	InvokeHelper(0x591, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 pNumberFormat);
}

CF1Rect CF1BookView::RangeToPixelsEx(long nRow1, long nCol1, long nRow2, long nCol2)
{
	LPDISPATCH pDispatch;
	static BYTE parms[] =
		VTS_I4 VTS_I4 VTS_I4 VTS_I4;
	InvokeHelper(0x592, DISPATCH_METHOD, VT_DISPATCH, (void*)&pDispatch, parms,
		nRow1, nCol1, nRow2, nCol2);
	return CF1Rect(pDispatch);
}

void CF1BookView::WriteEx(LPCTSTR PathName, long FileType)
{
	static BYTE parms[] =
		VTS_BSTR VTS_I4;
	InvokeHelper(0x594, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 PathName, FileType);
}

void CF1BookView::WriteRangeEx(long nSheet, long nRow1, long nCol1, long nRow2, long nCol2, LPCTSTR pPathName, long FileType)
{
	static BYTE parms[] =
		VTS_I4 VTS_I4 VTS_I4 VTS_I4 VTS_I4 VTS_BSTR VTS_I4;
	InvokeHelper(0x595, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 nSheet, nRow1, nCol1, nRow2, nCol2, pPathName, FileType);
}

void CF1BookView::GetFontEx(BSTR* pName, long* pCharSet, short* pSize, BOOL* pBold, BOOL* pItalic, BOOL* pUnderline, BOOL* pStrikeout, long* pcrColor, BOOL* pOutline, BOOL* pShadow)
{
	static BYTE parms[] =
		VTS_PBSTR VTS_PI4 VTS_PI2 VTS_PBOOL VTS_PBOOL VTS_PBOOL VTS_PBOOL VTS_PI4 VTS_PBOOL VTS_PBOOL;
	InvokeHelper(0x597, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 pName, pCharSet, pSize, pBold, pItalic, pUnderline, pStrikeout, pcrColor, pOutline, pShadow);
}

void CF1BookView::SetFontEx(LPCTSTR pName, long CharSet, short nSize, BOOL bBold, BOOL bItalic, BOOL bUnderline, BOOL bStrikeout, unsigned long crColor, BOOL bOutline, BOOL bShadow)
{
	static BYTE parms[] =
		VTS_BSTR VTS_I4 VTS_I2 VTS_BOOL VTS_BOOL VTS_BOOL VTS_BOOL VTS_I4 VTS_BOOL VTS_BOOL;
	InvokeHelper(0x598, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 pName, CharSet, nSize, bBold, bItalic, bUnderline, bStrikeout, crColor, bOutline, bShadow);
}

void CF1BookView::GetDefaultFontEx(BSTR* pBuf, long* pCharSet, short* pSize)
{
	static BYTE parms[] =
		VTS_PBSTR VTS_PI4 VTS_PI2;
	InvokeHelper(0x59a, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 pBuf, pCharSet, pSize);
}

void CF1BookView::SetDefaultFontEx(LPCTSTR Name, long CharSet, short nSize)
{
	static BYTE parms[] =
		VTS_BSTR VTS_I4 VTS_I2;
	InvokeHelper(0x59b, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 Name, CharSet, nSize);
}

CF1CellFormat CF1BookView::CreateNewCellFormat()
{
	LPDISPATCH pDispatch;
	InvokeHelper(0x59d, DISPATCH_METHOD, VT_DISPATCH, (void*)&pDispatch, NULL);
	return CF1CellFormat(pDispatch);
}

CF1CellFormat CF1BookView::GetCellFormat()
{
	LPDISPATCH pDispatch;
	InvokeHelper(0x59e, DISPATCH_METHOD, VT_DISPATCH, (void*)&pDispatch, NULL);
	return CF1CellFormat(pDispatch);
}

void CF1BookView::SetCellFormat(LPDISPATCH CellFormat)
{
	static BYTE parms[] =
		VTS_DISPATCH;
	InvokeHelper(0x59f, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 CellFormat);
}

CString CF1BookView::ErrorNumberToText(long SSError)
{
	CString result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x102, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		SSError);
	return result;
}
