// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CF1CellFormat wrapper class

class CF1CellFormat : public COleDispatchDriver
{
public:
	CF1CellFormat() {}		// Calls COleDispatchDriver default constructor
	CF1CellFormat(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CF1CellFormat(const CF1CellFormat& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	long GetAlignHorizontal();
	void SetAlignHorizontal(long nNewValue);
	BOOL GetWordWrap();
	void SetWordWrap(BOOL bNewValue);
	long GetAlignVertical();
	void SetAlignVertical(long nNewValue);
	long GetBorderStyle(long WhichBorder);
	void SetBorderStyle(long WhichBorder, long nNewValue);
	unsigned long GetBorderColor(long WhichBorder);
	void SetBorderColor(long WhichBorder, unsigned long newValue);
	CString GetFontName();
	void SetFontName(LPCTSTR lpszNewValue);
	long GetFontCharSet();
	void SetFontCharSet(long nNewValue);
	short GetFontSize();
	void SetFontSize(short nNewValue);
	BOOL GetFontBold();
	void SetFontBold(BOOL bNewValue);
	BOOL GetFontItalic();
	void SetFontItalic(BOOL bNewValue);
	BOOL GetFontUnderline();
	void SetFontUnderline(BOOL bNewValue);
	BOOL GetFontStrikeout();
	void SetFontStrikeout(BOOL bNewValue);
	unsigned long GetFontColor();
	void SetFontColor(unsigned long newValue);
	CString GetNumberFormat(long hSS);
	void SetNumberFormat(long hSS, LPCTSTR lpszNewValue);
	CString GetNumberFormatLocal(long hSS);
	void SetNumberFormatLocal(long hSS, LPCTSTR lpszNewValue);
	short GetPatternStyle();
	void SetPatternStyle(short nNewValue);
	unsigned long GetPatternFG();
	void SetPatternFG(unsigned long newValue);
	unsigned long GetPatternBG();
	void SetPatternBG(unsigned long newValue);
	BOOL GetProtectionLocked();
	void SetProtectionLocked(BOOL bNewValue);
	BOOL GetProtectionHidden();
	void SetProtectionHidden(BOOL bNewValue);
	CString GetValidationRule(long hSS);
	void SetValidationRule(long hSS, LPCTSTR lpszNewValue);
	CString GetValidationRuleLocal(long hSS);
	void SetValidationRuleLocal(long hSS, LPCTSTR lpszNewValue);
	CString GetValidationRuleRC(long hSS, long nRow, long nCol);
	void SetValidationRuleRC(long hSS, long nRow, long nCol, LPCTSTR lpszNewValue);
	CString GetValidationRuleLocalRC(long hSS, long nRow, long nCol);
	void SetValidationRuleLocalRC(long hSS, long nRow, long nCol, LPCTSTR lpszNewValue);
	CString GetValidationText();
	void SetValidationText(LPCTSTR lpszNewValue);
	BOOL GetIsDefined(long Attribute);
	void SetIsDefined(long Attribute, BOOL bNewValue);
	BOOL GetIsBorderDefined(long Border);
	void SetIsBorderDefined(long Border, BOOL bNewValue);
};
