#ifndef __F1FINDREPLACEINFO_H__
#define __F1FINDREPLACEINFO_H__

// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CF1FindReplaceInfo wrapper class

class CF1FindReplaceInfo : public COleDispatchDriver
{
public:
	CF1FindReplaceInfo() {}		// Calls COleDispatchDriver default constructor
	CF1FindReplaceInfo(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CF1FindReplaceInfo(const CF1FindReplaceInfo& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	// method 'QueryInterface' not emitted because of invalid return type or parameter type
	unsigned long AddRef();
	unsigned long Release();
	// method 'GetTypeInfoCount' not emitted because of invalid return type or parameter type
	// method 'GetTypeInfo' not emitted because of invalid return type or parameter type
	// method 'GetIDsOfNames' not emitted because of invalid return type or parameter type
	// method 'Invoke' not emitted because of invalid return type or parameter type
	BOOL FindNext();
	void Replace(LPCTSTR ReplaceWith);
	long GetRow();
	long GetCol();
};

#endif // __F1FINDREPLACEINFO_H__
