// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CF1FileSpec wrapper class

class CF1FileSpec : public COleDispatchDriver
{
public:
	CF1FileSpec() {}		// Calls COleDispatchDriver default constructor
	CF1FileSpec(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CF1FileSpec(const CF1FileSpec& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	CString GetName();
	long GetType();
	void SetName(LPCTSTR lpszNewValue);
	void SetType(long nNewValue);
};
