// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CF1NumberFormat wrapper class

class CF1NumberFormat : public COleDispatchDriver
{
public:
	CF1NumberFormat() {}		// Calls COleDispatchDriver default constructor
	CF1NumberFormat(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CF1NumberFormat(const CF1NumberFormat& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	CString GetNumberFormat();
	CString GetNumberFormatLocal();
	long GetType();
};
