// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CF1ODBCConnect wrapper class

class CF1ODBCConnect : public COleDispatchDriver
{
public:
	CF1ODBCConnect() {}		// Calls COleDispatchDriver default constructor
	CF1ODBCConnect(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CF1ODBCConnect(const CF1ODBCConnect& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	CString GetConnectStr();
	void SetConnectStr(LPCTSTR lpszNewValue);
	short GetRetCode();
	void SetRetCode(short nNewValue);
};
