// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CF1ODBCQuery wrapper class

class CF1ODBCQuery : public COleDispatchDriver
{
public:
	CF1ODBCQuery() {}		// Calls COleDispatchDriver default constructor
	CF1ODBCQuery(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CF1ODBCQuery(const CF1ODBCQuery& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	CString GetQueryStr();
	void SetQueryStr(LPCTSTR lpszNewValue);
	BOOL GetSetColNames();
	void SetSetColNames(BOOL bNewValue);
	BOOL GetSetColFormats();
	void SetSetColFormats(BOOL bNewValue);
	BOOL GetSetColWidths();
	void SetSetColWidths(BOOL bNewValue);
	BOOL GetSetMaxRC();
	void SetSetMaxRC(BOOL bNewValue);
	short GetRetCode();
	void SetRetCode(short nNewValue);
};
