#ifndef __F1PAGESETUP_H__
#define __F1PAGESETUP_H__

// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CF1PageSetup wrapper class

class CF1PageSetup : public COleDispatchDriver
{
public:
	CF1PageSetup() {}		// Calls COleDispatchDriver default constructor
	CF1PageSetup(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CF1PageSetup(const CF1PageSetup& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	// method 'QueryInterface' not emitted because of invalid return type or parameter type
	unsigned long AddRef();
	unsigned long Release();
	// method 'GetTypeInfoCount' not emitted because of invalid return type or parameter type
	// method 'GetTypeInfo' not emitted because of invalid return type or parameter type
	// method 'GetIDsOfNames' not emitted because of invalid return type or parameter type
	// method 'Invoke' not emitted because of invalid return type or parameter type
	BOOL GetLandscape();
	void SetLandscape(BOOL bNewValue);
	BOOL GetFitPages();
	void SetFitPages(BOOL bNewValue);
	short GetPrintScale();
	void SetPrintScale(short nNewValue);
	long GetPagesWide();
	void SetPagesWide(long nNewValue);
	long GetPagesTall();
	void SetPagesTall(long nNewValue);
	long GetPaperSize();
	void SetPaperSize(long nNewValue);
	long GetFirstPageNumber();
	void SetFirstPageNumber(long nNewValue);
	BOOL GetAutoPageNumber();
	void SetAutoPageNumber(BOOL bNewValue);
	double GetLeftMargin();
	void SetLeftMargin(double newValue);
	double GetTopMargin();
	void SetTopMargin(double newValue);
	double GetRightMargin();
	void SetRightMargin(double newValue);
	double GetBottomMargin();
	void SetBottomMargin(double newValue);
	double GetHeaderMargin();
	void SetHeaderMargin(double newValue);
	double GetFooterMargin();
	void SetFooterMargin(double newValue);
	BOOL GetCenterHoriz();
	void SetCenterHoriz(BOOL bNewValue);
	BOOL GetCenterVert();
	void SetCenterVert(BOOL bNewValue);
	CString GetHeader();
	void SetHeader(LPCTSTR lpszNewValue);
	CString GetFooter();
	void SetFooter(LPCTSTR lpszNewValue);
	BOOL GetGridLines();
	void SetGridLines(BOOL bNewValue);
	BOOL GetBlackAndWhite();
	void SetBlackAndWhite(BOOL bNewValue);
	BOOL GetRowHeadings();
	void SetRowHeadings(BOOL bNewValue);
	BOOL GetColHeadings();
	void SetColHeadings(BOOL bNewValue);
	BOOL GetLeftToRight();
	void SetLeftToRight(BOOL bNewValue);
	BOOL GetIsDefined(long Attribute);
	void SetIsDefined(long Attribute, BOOL bNewValue);
	CString GetPrintArea();
	void SetPrintArea(LPCTSTR lpszNewValue);
	CString GetPrintAreaLocal();
	void SetPrintAreaLocal(LPCTSTR lpszNewValue);
	CString GetPrintTitles();
	void SetPrintTitles(LPCTSTR lpszNewValue);
	CString GetPrintTitlesLocal();
	void SetPrintTitlesLocal(LPCTSTR lpszNewValue);
};

#endif // __F1PAGESETUP_H__
