// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CF1RangeRef wrapper class

class CF1RangeRef : public COleDispatchDriver
{
public:
	CF1RangeRef() {}		// Calls COleDispatchDriver default constructor
	CF1RangeRef(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CF1RangeRef(const CF1RangeRef& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	long GetStartRow();
	long GetStartCol();
	long GetEndRow();
	long GetEndCol();
	long GetRows();
	long GetCols();
};
