// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CF1Rect wrapper class

class CF1Rect : public COleDispatchDriver
{
public:
	CF1Rect() {}		// Calls COleDispatchDriver default constructor
	CF1Rect(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CF1Rect(const CF1Rect& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	long GetTop();
	long GetLeft();
	long GetBottom();
	long GetRight();
	long GetHeight();
	long GetWidth();
};
