// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CF1ReplaceResults wrapper class

class CF1ReplaceResults : public COleDispatchDriver
{
public:
	CF1ReplaceResults() {}		// Calls COleDispatchDriver default constructor
	CF1ReplaceResults(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CF1ReplaceResults(const CF1ReplaceResults& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	long GetFound();
	long GetReplaced();
};
