#if !defined(AFX_FLATSB_H__9104B61F_ADA9_4674_AD80_ADAC2A47AE23__INCLUDED_)
#define AFX_FLATSB_H__9104B61F_ADA9_4674_AD80_ADAC2A47AE23__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CPicture1;

/////////////////////////////////////////////////////////////////////////////
// CFlatSB wrapper class

class CFlatSB : public CWnd
{
protected:
	DECLARE_DYNCREATE(CFlatSB)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0xfe38753a, 0x44a3, 0x11d1, { 0xb5, 0xb7, 0x0, 0x0, 0xc0, 0x90, 0x0, 0xc4 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:

// Operations
public:
	long GetAppearance();
	void SetAppearance(long nNewValue);
	long GetArrows();
	void SetArrows(long nNewValue);
	BOOL GetEnabled();
	void SetEnabled(BOOL bNewValue);
	long GetHWnd();
	void SetHWnd(long nNewValue);
	short GetLargeChange();
	void SetLargeChange(short nNewValue);
	short GetMin();
	void SetMin(short nNewValue);
	short GetMax();
	void SetMax(short nNewValue);
	CPicture1 GetMouseIcon();
	void SetMouseIcon(LPDISPATCH newValue);
	void SetRefMouseIcon(LPDISPATCH newValue);
	long GetMousePointer();
	void SetMousePointer(long nNewValue);
	long GetOrientation();
	void SetOrientation(long nNewValue);
	short GetSmallChange();
	void SetSmallChange(short nNewValue);
	short GetValue();
	void SetValue(short nNewValue);
	void Refresh();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_FLATSB_H__9104B61F_ADA9_4674_AD80_ADAC2A47AE23__INCLUDED_)
