#if !defined(AFX_FONT1_H__CF5144E3_F6A6_4C3E_A551_AFA7AB601B89__INCLUDED_)
#define AFX_FONT1_H__CF5144E3_F6A6_4C3E_A551_AFA7AB601B89__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// COleFont1 wrapper class

class COleFont1 : public COleDispatchDriver
{
public:
	COleFont1() {}		// Calls COleDispatchDriver default constructor
	COleFont1(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	COleFont1(const COleFont1& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:
	CString GetName();
	void SetName(LPCTSTR);
	CY GetSize();
	void SetSize(const CY&);
	BOOL GetBold();
	void SetBold(BOOL);
	BOOL GetItalic();
	void SetItalic(BOOL);
	BOOL GetUnderline();
	void SetUnderline(BOOL);
	BOOL GetStrikethrough();
	void SetStrikethrough(BOOL);
	short GetWeight();
	void SetWeight(short);
	short GetCharset();
	void SetCharset(short);

// Operations
public:
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_FONT1_H__CF5144E3_F6A6_4C3E_A551_AFA7AB601B89__INCLUDED_)
