#if !defined(AFX_SDIGRID_H__96F5F62A_BCFE_4520_9510_D82843842B55__INCLUDED_)
#define AFX_SDIGRID_H__96F5F62A_BCFE_4520_9510_D82843842B55__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CSDIGrid wrapper class

class CSDIGrid : public CWnd
{
protected:
	DECLARE_DYNCREATE(CSDIGrid)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0xc3e95cf6, 0x64bc, 0x11d3, { 0x8d, 0x9c, 0x4e, 0xe4, 0xb9, 0x0, 0x0, 0x0 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:
	long GetReadyState();
	short GetNumRows();
	void SetNumRows(short);
	short GetNumCols();
	void SetNumCols(short);
	BOOL GetColZeroIsFixed();
	void SetColZeroIsFixed(BOOL);
	short GetFixedColHeight();
	void SetFixedColHeight(short);

// Operations
public:
	short GetCellType(short nRow, short nCol);
	CString GetCellContents(short Row, short Col);
	void SetCellContents(short Row, short Col, LPCTSTR Contents);
	long GetAddress();
	void ClearGrid();
	void AboutBox();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_SDIGRID_H__96F5F62A_BCFE_4520_9510_D82843842B55__INCLUDED_)
