// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "sdigrid.h"

/////////////////////////////////////////////////////////////////////////////
// CSDIGrid

IMPLEMENT_DYNCREATE(CSDIGrid, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CSDIGrid properties

long CSDIGrid::GetReadyState()
{
	long result;
	GetProperty(DISPID_READYSTATE, VT_I4, (void*)&result);
	return result;
}

short CSDIGrid::GetNumRows()
{
	short result;
	GetProperty(0x1, VT_I2, (void*)&result);
	return result;
}

void CSDIGrid::SetNumRows(short propVal)
{
	SetProperty(0x1, VT_I2, propVal);
}

short CSDIGrid::GetNumCols()
{
	short result;
	GetProperty(0x2, VT_I2, (void*)&result);
	return result;
}

void CSDIGrid::SetNumCols(short propVal)
{
	SetProperty(0x2, VT_I2, propVal);
}

BOOL CSDIGrid::GetColZeroIsFixed()
{
	BOOL result;
	GetProperty(0x3, VT_BOOL, (void*)&result);
	return result;
}

void CSDIGrid::SetColZeroIsFixed(BOOL propVal)
{
	SetProperty(0x3, VT_BOOL, propVal);
}

short CSDIGrid::GetFixedColHeight()
{
	short result;
	GetProperty(0x4, VT_I2, (void*)&result);
	return result;
}

void CSDIGrid::SetFixedColHeight(short propVal)
{
	SetProperty(0x4, VT_I2, propVal);
}

/////////////////////////////////////////////////////////////////////////////
// CSDIGrid operations

short CSDIGrid::GetCellType(short nRow, short nCol)
{
	short result;
	static BYTE parms[] =
		VTS_I2 VTS_I2;
	InvokeHelper(0x5, DISPATCH_METHOD, VT_I2, (void*)&result, parms,
		nRow, nCol);
	return result;
}

CString CSDIGrid::GetCellContents(short Row, short Col)
{
	CString result;
	static BYTE parms[] =
		VTS_I2 VTS_I2;
	InvokeHelper(0x6, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		Row, Col);
	return result;
}

void CSDIGrid::SetCellContents(short Row, short Col, LPCTSTR Contents)
{
	static BYTE parms[] =
		VTS_I2 VTS_I2 VTS_BSTR;
	InvokeHelper(0x7, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 Row, Col, Contents);
}

long CSDIGrid::GetAddress()
{
	long result;
	InvokeHelper(0x8, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

void CSDIGrid::ClearGrid()
{
	InvokeHelper(0x9, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CSDIGrid::AboutBox()
{
	InvokeHelper(0xfffffdd8, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}
